"""initial schema

Revision ID: 8ef0a7a390cb
Revises: 
Create Date: 2026-07-26 21:16:03.293102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8ef0a7a390cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('garden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('usda_zone', sa.String(length=10), nullable=True),
    sa.Column('zone_temp_range', sa.String(length=50), nullable=True),
    sa.Column('last_frost_date', sa.Date(), nullable=True),
    sa.Column('first_frost_date', sa.Date(), nullable=True),
    sa.Column('frost_free', sa.Boolean(), nullable=True),
    sa.Column('frost_station_id', sa.String(length=20), nullable=True),
    sa.Column('frost_station_name', sa.String(length=100), nullable=True),
    sa.Column('frost_station_distance_km', sa.Float(), nullable=True),
    sa.Column('last_frost_dates_json', sa.Text(), nullable=True),
    sa.Column('first_frost_dates_json', sa.Text(), nullable=True),
    sa.Column('watering_frequency_days', sa.Integer(), nullable=True),
    sa.Column('water_source', sa.String(length=30), nullable=True),
    sa.Column('background_image', sa.String(length=200), nullable=True),
    sa.Column('background_color', sa.String(length=20), nullable=True),
    sa.Column('background_pattern', sa.String(length=30), nullable=True),
    sa.Column('annotations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('perenual_id', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('spacing_in', sa.Integer(), nullable=True),
    sa.Column('sunlight', sa.String(length=50), nullable=True),
    sa.Column('water', sa.String(length=50), nullable=True),
    sa.Column('days_to_germination', sa.Integer(), nullable=True),
    sa.Column('days_to_harvest', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('min_zone', sa.Integer(), nullable=True),
    sa.Column('max_zone', sa.Integer(), nullable=True),
    sa.Column('temp_min_f', sa.Integer(), nullable=True),
    sa.Column('temp_max_f', sa.Integer(), nullable=True),
    sa.Column('soil_ph_min', sa.Float(), nullable=True),
    sa.Column('soil_ph_max', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(length=200), nullable=True),
    sa.Column('good_neighbors', sa.Text(), nullable=True),
    sa.Column('bad_neighbors', sa.Text(), nullable=True),
    sa.Column('sow_indoor_weeks', sa.Integer(), nullable=True),
    sa.Column('direct_sow_offset', sa.Integer(), nullable=True),
    sa.Column('transplant_offset', sa.Integer(), nullable=True),
    sa.Column('how_to_grow', sa.Text(), nullable=True),
    sa.Column('faqs', sa.Text(), nullable=True),
    sa.Column('nutrition', sa.Text(), nullable=True),
    sa.Column('usda_fdc_id', sa.Integer(), nullable=True),
    sa.Column('permapeople_id', sa.Integer(), nullable=True),
    sa.Column('permapeople_link', sa.String(length=200), nullable=True),
    sa.Column('permapeople_description', sa.Text(), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('layer', sa.String(length=100), nullable=True),
    sa.Column('edible_parts', sa.String(length=200), nullable=True),
    sa.Column('openfarm_id', sa.String(length=30), nullable=True),
    sa.Column('openfarm_slug', sa.String(length=100), nullable=True),
    sa.Column('trefle_id', sa.Integer(), nullable=True),
    sa.Column('trefle_slug', sa.String(length=100), nullable=True),
    sa.Column('genus', sa.String(length=100), nullable=True),
    sa.Column('edible', sa.Boolean(), nullable=True),
    sa.Column('toxicity', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('ligneous_type', sa.String(length=50), nullable=True),
    sa.Column('growth_habit', sa.String(length=100), nullable=True),
    sa.Column('growth_form', sa.String(length=100), nullable=True),
    sa.Column('growth_rate', sa.String(length=50), nullable=True),
    sa.Column('nitrogen_fixation', sa.String(length=30), nullable=True),
    sa.Column('vegetable', sa.Boolean(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('average_height_cm', sa.Integer(), nullable=True),
    sa.Column('maximum_height_cm', sa.Integer(), nullable=True),
    sa.Column('spread_cm', sa.Integer(), nullable=True),
    sa.Column('row_spacing_cm', sa.Integer(), nullable=True),
    sa.Column('minimum_root_depth_cm', sa.Integer(), nullable=True),
    sa.Column('soil_nutriments', sa.Integer(), nullable=True),
    sa.Column('soil_salinity', sa.Integer(), nullable=True),
    sa.Column('atmospheric_humidity', sa.Integer(), nullable=True),
    sa.Column('precipitation_min_mm', sa.Integer(), nullable=True),
    sa.Column('precipitation_max_mm', sa.Integer(), nullable=True),
    sa.Column('bloom_months', sa.Text(), nullable=True),
    sa.Column('fruit_months', sa.Text(), nullable=True),
    sa.Column('growth_months', sa.Text(), nullable=True),
    sa.Column('flower_color', sa.String(length=100), nullable=True),
    sa.Column('flower_conspicuous', sa.Boolean(), nullable=True),
    sa.Column('foliage_color', sa.String(length=100), nullable=True),
    sa.Column('foliage_texture', sa.String(length=30), nullable=True),
    sa.Column('leaf_retention', sa.Boolean(), nullable=True),
    sa.Column('fruit_color', sa.String(length=100), nullable=True),
    sa.Column('fruit_conspicuous', sa.Boolean(), nullable=True),
    sa.Column('fruit_shape', sa.String(length=100), nullable=True),
    sa.Column('seed_persistence', sa.Boolean(), nullable=True),
    sa.Column('poisonous_to_pets', sa.Boolean(), nullable=True),
    sa.Column('poisonous_to_humans', sa.Boolean(), nullable=True),
    sa.Column('drought_tolerant', sa.Boolean(), nullable=True),
    sa.Column('salt_tolerant', sa.Boolean(), nullable=True),
    sa.Column('thorny', sa.Boolean(), nullable=True),
    sa.Column('invasive', sa.Boolean(), nullable=True),
    sa.Column('rare', sa.Boolean(), nullable=True),
    sa.Column('tropical', sa.Boolean(), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.Column('cuisine', sa.Boolean(), nullable=True),
    sa.Column('medicinal', sa.Boolean(), nullable=True),
    sa.Column('attracts', sa.Text(), nullable=True),
    sa.Column('propagation_methods', sa.Text(), nullable=True),
    sa.Column('harvest_season', sa.String(length=50), nullable=True),
    sa.Column('harvest_method', sa.String(length=100), nullable=True),
    sa.Column('fruiting_season', sa.String(length=50), nullable=True),
    sa.Column('pruning_months', sa.Text(), nullable=True),
    sa.Column('cloned_from_id', sa.Integer(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['plant_library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_token_token_hash'), 'auth_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_token_user_id'), 'auth_token', ['user_id'], unique=False)
    op.create_table('compost_bin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('started_date', sa.Date(), nullable=True),
    sa.Column('estimated_ready_date', sa.Date(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compost_bin_garden_id'), 'compost_bin', ['garden_id'], unique=False)
    op.create_table('garden_bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.Column('width_ft', sa.Float(), nullable=False),
    sa.Column('height_ft', sa.Float(), nullable=False),
    sa.Column('depth_ft', sa.Float(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('soil_notes', sa.Text(), nullable=True),
    sa.Column('soil_ph', sa.Float(), nullable=True),
    sa.Column('clay_pct', sa.Float(), nullable=True),
    sa.Column('compost_pct', sa.Float(), nullable=True),
    sa.Column('sand_pct', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('background_image', sa.String(length=200), nullable=True),
    sa.Column('background_pattern', sa.String(length=30), nullable=True),
    sa.Column('last_weeded', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garden_bed_garden_id'), 'garden_bed', ['garden_id'], unique=False)
    op.create_table('garden_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garden_id', 'user_id', name='uq_garden_member')
    )
    op.create_index(op.f('ix_garden_member_garden_id'), 'garden_member', ['garden_id'], unique=False)
    op.create_index(op.f('ix_garden_member_user_id'), 'garden_member', ['user_id'], unique=False)
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('planted_date', sa.Date(), nullable=True),
    sa.Column('transplant_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_watered', sa.Date(), nullable=True),
    sa.Column('watering_amount', sa.String(length=20), nullable=True),
    sa.Column('last_fertilized', sa.Date(), nullable=True),
    sa.Column('fertilizer_type', sa.String(length=50), nullable=True),
    sa.Column('fertilizer_npk', sa.String(length=20), nullable=True),
    sa.Column('succession_label', sa.String(length=50), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['plant_library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_garden_id'), 'plant', ['garden_id'], unique=False)
    op.create_index(op.f('ix_plant_library_id'), 'plant', ['library_id'], unique=False)
    op.create_table('plant_library_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_library_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_library_id'], ['plant_library.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('seed_tray',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('plant_name', sa.String(length=100), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('sow_date', sa.Date(), nullable=True),
    sa.Column('germination_date', sa.Date(), nullable=True),
    sa.Column('transplant_ready_date', sa.Date(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['plant_library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_tray_garden_id'), 'seed_tray', ['garden_id'], unique=False)
    op.create_index(op.f('ix_seed_tray_library_id'), 'seed_tray', ['library_id'], unique=False)
    op.create_table('weather_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rainfall_in', sa.Float(), nullable=True),
    sa.Column('temp_high_f', sa.Float(), nullable=True),
    sa.Column('temp_low_f', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('et0_mm', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garden_id', 'date', name='uq_weatherlog_garden_date')
    )
    op.create_table('bed_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=True),
    sa.Column('grid_y', sa.Integer(), nullable=True),
    sa.Column('last_watered', sa.Date(), nullable=True),
    sa.Column('watering_amount', sa.String(length=20), nullable=True),
    sa.Column('last_fertilized', sa.Date(), nullable=True),
    sa.Column('fertilizer_type', sa.String(length=50), nullable=True),
    sa.Column('fertilizer_npk', sa.String(length=20), nullable=True),
    sa.Column('last_harvest', sa.Date(), nullable=True),
    sa.Column('health_notes', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['garden_bed.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_plant_bed_id'), 'bed_plant', ['bed_id'], unique=False)
    op.create_index(op.f('ix_bed_plant_plant_id'), 'bed_plant', ['plant_id'], unique=False)
    op.create_table('canvas_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('radius_ft', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('display_mode', sa.String(length=10), nullable=False),
    sa.Column('custom_image', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['plant_library.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvas_plant_garden_id'), 'canvas_plant', ['garden_id'], unique=False)
    op.create_index(op.f('ix_canvas_plant_library_id'), 'canvas_plant', ['library_id'], unique=False)
    op.create_index(op.f('ix_canvas_plant_plant_id'), 'canvas_plant', ['plant_id'], unique=False)
    op.create_table('journal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_garden_id'), 'journal_entry', ['garden_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_plant_id'), 'journal_entry', ['plant_id'], unique=False)
    op.create_table('ml_watering_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('rain_7d_mm', sa.Float(), nullable=True),
    sa.Column('et0_7d_mm', sa.Float(), nullable=True),
    sa.Column('temp_high_f', sa.Float(), nullable=True),
    sa.Column('temp_low_f', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('forecast_precip_mm_d0', sa.Float(), nullable=True),
    sa.Column('forecast_precip_prob_d0', sa.Float(), nullable=True),
    sa.Column('forecast_precip_mm_d1_d2', sa.Float(), nullable=True),
    sa.Column('forecast_temp_max_c', sa.Float(), nullable=True),
    sa.Column('days_since_watered', sa.Integer(), nullable=True),
    sa.Column('maturity_days', sa.Integer(), nullable=True),
    sa.Column('seedling_frac', sa.Float(), nullable=True),
    sa.Column('kc_avg', sa.Float(), nullable=True),
    sa.Column('mm_day_avg', sa.Float(), nullable=True),
    sa.Column('sand_pct', sa.Float(), nullable=True),
    sa.Column('clay_pct', sa.Float(), nullable=True),
    sa.Column('bed_area_m2', sa.Float(), nullable=True),
    sa.Column('rule_deficit_mm', sa.Float(), nullable=True),
    sa.Column('rule_score', sa.Integer(), nullable=True),
    sa.Column('model_pred_mm', sa.Float(), nullable=True),
    sa.Column('model_used', sa.Boolean(), nullable=False),
    sa.Column('watered_next_day', sa.Boolean(), nullable=True),
    sa.Column('watered_amount', sa.String(length=20), nullable=True),
    sa.Column('rain_next_day_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['garden_bed.id'], ),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garden_id', 'bed_id', 'snapshot_date', name='uq_ml_snapshot_garden_bed_date')
    )
    op.create_index(op.f('ix_ml_watering_snapshot_bed_id'), 'ml_watering_snapshot', ['bed_id'], unique=False)
    op.create_index(op.f('ix_ml_watering_snapshot_garden_id'), 'ml_watering_snapshot', ['garden_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.Column('bed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['garden_bed.id'], ),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_bed_id'), 'task', ['bed_id'], unique=False)
    op.create_index(op.f('ix_task_garden_id'), 'task', ['garden_id'], unique=False)
    op.create_index(op.f('ix_task_plant_id'), 'task', ['plant_id'], unique=False)
    op.create_table('watering_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['garden_bed.id'], ),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watering_event_bed_id'), 'watering_event', ['bed_id'], unique=False)
    op.create_index(op.f('ix_watering_event_garden_id'), 'watering_event', ['garden_id'], unique=False)
    op.create_table('plant_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_plant_id', sa.Integer(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('observation_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bed_plant_id'], ['bed_plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_observation_bed_plant_id'), 'plant_observation', ['bed_plant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_observation_bed_plant_id'), table_name='plant_observation')
    op.drop_table('plant_observation')
    op.drop_index(op.f('ix_watering_event_garden_id'), table_name='watering_event')
    op.drop_index(op.f('ix_watering_event_bed_id'), table_name='watering_event')
    op.drop_table('watering_event')
    op.drop_index(op.f('ix_task_plant_id'), table_name='task')
    op.drop_index(op.f('ix_task_garden_id'), table_name='task')
    op.drop_index(op.f('ix_task_bed_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_ml_watering_snapshot_garden_id'), table_name='ml_watering_snapshot')
    op.drop_index(op.f('ix_ml_watering_snapshot_bed_id'), table_name='ml_watering_snapshot')
    op.drop_table('ml_watering_snapshot')
    op.drop_index(op.f('ix_journal_entry_plant_id'), table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_garden_id'), table_name='journal_entry')
    op.drop_table('journal_entry')
    op.drop_index(op.f('ix_canvas_plant_plant_id'), table_name='canvas_plant')
    op.drop_index(op.f('ix_canvas_plant_library_id'), table_name='canvas_plant')
    op.drop_index(op.f('ix_canvas_plant_garden_id'), table_name='canvas_plant')
    op.drop_table('canvas_plant')
    op.drop_index(op.f('ix_bed_plant_plant_id'), table_name='bed_plant')
    op.drop_index(op.f('ix_bed_plant_bed_id'), table_name='bed_plant')
    op.drop_table('bed_plant')
    op.drop_table('weather_log')
    op.drop_index(op.f('ix_seed_tray_library_id'), table_name='seed_tray')
    op.drop_index(op.f('ix_seed_tray_garden_id'), table_name='seed_tray')
    op.drop_table('seed_tray')
    op.drop_table('plant_library_image')
    op.drop_index(op.f('ix_plant_library_id'), table_name='plant')
    op.drop_index(op.f('ix_plant_garden_id'), table_name='plant')
    op.drop_table('plant')
    op.drop_index(op.f('ix_garden_member_user_id'), table_name='garden_member')
    op.drop_index(op.f('ix_garden_member_garden_id'), table_name='garden_member')
    op.drop_table('garden_member')
    op.drop_index(op.f('ix_garden_bed_garden_id'), table_name='garden_bed')
    op.drop_table('garden_bed')
    op.drop_index(op.f('ix_compost_bin_garden_id'), table_name='compost_bin')
    op.drop_table('compost_bin')
    op.drop_index(op.f('ix_auth_token_user_id'), table_name='auth_token')
    op.drop_index(op.f('ix_auth_token_token_hash'), table_name='auth_token')
    op.drop_table('auth_token')
    op.drop_table('plant_library')
    op.drop_table('garden')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
