"""add guide_chunk table with pgvector embeddings

Replaces the ChromaDB growing-guides store. Written by hand rather than
autogenerated: autogenerate cannot emit CREATE EXTENSION, and it cannot reflect
a vector column before the extension exists.

Repopulate after upgrading with:
    uv run python scripts/build_rag.py --rebuild

Revision ID: b41c7d92e5a3
Revises: 8ef0a7a390cb
Create Date: 2026-08-01 10:14:22.881470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


revision: str = 'b41c7d92e5a3'
down_revision: Union[str, None] = '8ef0a7a390cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    op.create_table(
        'guide_chunk',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('source', sa.String(length=200), nullable=True),
        sa.Column('plant_name', sa.String(length=100), nullable=True),
        sa.Column('region', sa.String(length=50), nullable=True),
        sa.Column('page', sa.Integer(), nullable=True),
        # Width must match EMBED_DIMS in apps/ml_service/app/embed_provider.py.
        sa.Column('embedding', Vector(768), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_guide_chunk_region', 'guide_chunk', ['region'])

    # Cosine distance, matching the {'hnsw:space': 'cosine'} the Chroma
    # collection used, so relevance scores stay comparable to the old store.
    op.execute(
        'CREATE INDEX ix_guide_chunk_embedding ON guide_chunk '
        'USING hnsw (embedding vector_cosine_ops)'
    )


def downgrade() -> None:
    op.drop_index('ix_guide_chunk_embedding', table_name='guide_chunk')
    op.drop_index('ix_guide_chunk_region', table_name='guide_chunk')
    op.drop_table('guide_chunk')
    # The vector extension is left installed on purpose — dropping it would
    # break any other table that adopts a vector column later.
