"""Populate extended plant library data for all 44 plants."""
import sqlite3, json

DB = 'instance/garden.db'

# Each entry keyed by plant name (must match plant_library.name exactly)
# sow_indoor_weeks: weeks before last spring frost to start indoors (None = no indoor start)
# direct_sow_offset: weeks relative to last spring frost (negative = before, positive = after; None = no direct sow)
# transplant_offset: weeks after last spring frost to transplant out (None = direct sow only)
PLANTS = {
'Tomato': dict(
    difficulty='Moderate', min_zone=3, max_zone=11, temp_min_f=50, temp_max_f=95,
    soil_ph_min=6.0, soil_ph_max=6.8, soil_type='Well-draining fertile loam, rich in organic matter',
    good_neighbors=['Basil','Carrot','Parsley','Marigold','Garlic','Borage'],
    bad_neighbors=['Fennel','Cabbage','Broccoli','Cauliflower','Corn','Potato'],
    sow_indoor_weeks=8, direct_sow_offset=None, transplant_offset=2,
    how_to_grow=dict(
        starting='Start seeds indoors 6–8 weeks before last frost. Sow ¼" deep in seed-starting mix at 70–80°F. Germination takes 5–10 days. Provide 14–16 hours of light daily once sprouted.',
        seedling='Pot up to 4" containers once 2 sets of true leaves appear. Keep soil evenly moist and temperatures above 60°F. Harden off outdoors for 7–10 days before transplanting.',
        vegetative='Transplant after last frost into full sun. Bury stem up to lowest leaves to encourage deep roots. Stake or cage immediately. Water deeply 1–2× per week; side-dress with compost at 12" height.',
        flowering='Flowers appear 40–60 days after transplanting. Shake plants gently to aid pollination. Remove suckers on indeterminate varieties. Avoid high nitrogen at this stage; switch to a phosphorus-rich fertilizer.',
        harvest='Harvest when fully colored and slightly soft to touch. Twist gently or cut from vine. Pick regularly to encourage continued fruiting. Flavor is best at room temperature.',
    ),
    faqs=[
        dict(q='Why are my tomato leaves curling?', a='Leaf curl is usually heat stress, overwatering, or inconsistent watering. Ensure even moisture and good airflow. Physiological leaf roll (lower leaves curling upward) is harmless.'),
        dict(q='What causes blossom end rot?', a='Calcium deficiency caused by inconsistent watering, not a lack of soil calcium. Water evenly and mulch to maintain consistent soil moisture.'),
        dict(q='Should I remove suckers?', a='On indeterminate varieties, removing suckers (shoots between stem and branch) keeps plants focused. On determinate types, leave them to maximize yield.'),
        dict(q='How do I prevent tomato blight?', a='Avoid overhead watering, space plants for airflow, remove affected leaves promptly, rotate crops yearly, and apply copper fungicide preventatively in wet seasons.'),
    ],
    nutrition=dict(serving_size='1 medium tomato (123g)', calories=22, protein_g=1.1, carbs_g=4.8, fiber_g=1.5, fat_g=0.2,
        vitamins=['Vitamin C: 28% DV','Vitamin A: 20% DV','Potassium: 8% DV','Vitamin K: 10% DV'],
        notes='Rich in lycopene (especially when cooked), an antioxidant linked to reduced risk of heart disease and certain cancers.'),
),
'Cherry Tomato': dict(
    difficulty='Easy', min_zone=3, max_zone=11, temp_min_f=50, temp_max_f=95,
    soil_ph_min=6.0, soil_ph_max=6.8, soil_type='Well-draining loam, rich in compost',
    good_neighbors=['Basil','Carrot','Parsley','Marigold'],
    bad_neighbors=['Fennel','Potato','Brassicas'],
    sow_indoor_weeks=8, direct_sow_offset=None, transplant_offset=2,
    how_to_grow=dict(
        starting='Start indoors 6–8 weeks before last frost. Sow ¼" deep at 75–80°F. Germination in 5–10 days.',
        seedling='Thin to strongest seedling per cell. Pot up once true leaves appear. Harden off 7–10 days before transplanting.',
        vegetative='Plant in full sun after frost danger passes. Bury stem deeply. Water consistently and fertilize every 2–3 weeks.',
        flowering='Prolific flowering begins about 6 weeks after transplanting. Pollination is aided by wind and bees. Remove dead flowers to keep fruiting.',
        harvest='Pick fruits when fully colored and plump. Cherry tomatoes ripen faster than slicers — check daily once fruiting begins.',
    ),
    faqs=[
        dict(q='Why do my cherry tomatoes split?', a='Splitting is caused by irregular watering — a dry spell followed by heavy watering causes rapid fruit expansion. Keep moisture consistent and mulch well.'),
        dict(q='Can I grow cherry tomatoes in containers?', a='Yes — they thrive in 5-gallon or larger containers. Choose a compact or patio variety and ensure daily watering in hot weather.'),
        dict(q='How many cherry tomatoes will one plant produce?', a='A healthy plant can produce 100–300+ fruits per season depending on variety and conditions.'),
    ],
    nutrition=dict(serving_size='1 cup cherry tomatoes (149g)', calories=27, protein_g=1.3, carbs_g=5.8, fiber_g=1.8, fat_g=0.3,
        vitamins=['Vitamin C: 32% DV','Vitamin A: 25% DV','Potassium: 10% DV'],
        notes='High in lycopene and beta-carotene. The small size means a higher skin-to-flesh ratio, concentrating antioxidants.'),
),
'Bell Pepper': dict(
    difficulty='Moderate', min_zone=4, max_zone=11, temp_min_f=55, temp_max_f=90,
    soil_ph_min=6.0, soil_ph_max=6.8, soil_type='Well-draining sandy loam, warm and fertile',
    good_neighbors=['Basil','Carrot','Tomato','Marigold','Spinach'],
    bad_neighbors=['Fennel','Brassicas','Apricot'],
    sow_indoor_weeks=10, direct_sow_offset=None, transplant_offset=2,
    how_to_grow=dict(
        starting='Start seeds indoors 10–12 weeks before last frost at 80–85°F. Germination is slow (10–21 days). Use a heat mat.',
        seedling='Keep seedlings at 70°F+. Pot up to 4" containers at 3–4 true leaves. Harden off 10 days before transplanting.',
        vegetative='Transplant into full sun only after soil is consistently above 60°F. Peppers are very frost-sensitive. Stake when 12" tall.',
        flowering='White flowers appear in summer. Avoid over-fertilizing with nitrogen once flowering begins. Hand-pollinate in low-wind areas.',
        harvest='Green peppers are unripe — leave on plant to turn yellow, orange, or red for sweeter, higher-vitamin flavor.',
    ),
    faqs=[
        dict(q='Why are my pepper flowers dropping?', a='Flower drop happens when temperatures exceed 90°F or drop below 55°F, or due to inconsistent watering or low humidity.'),
        dict(q='How long do peppers take to turn red?', a='After reaching full green size, peppers take 2–4 more weeks to turn red. The wait is worth it — red peppers have 3× more vitamin C than green.'),
        dict(q='Can peppers survive light frost?', a='No — peppers are very frost-sensitive. Cover or bring indoors if temps will drop below 40°F.'),
    ],
    nutrition=dict(serving_size='1 medium pepper (119g)', calories=31, protein_g=1.0, carbs_g=7.2, fiber_g=2.5, fat_g=0.3,
        vitamins=['Vitamin C: 169% DV (red)','Vitamin A: 11% DV','Vitamin B6: 20% DV','Folate: 12% DV'],
        notes='Red bell peppers have among the highest vitamin C content of any vegetable. All colors are rich in antioxidants.'),
),
'Jalapeño': dict(
    difficulty='Easy', min_zone=4, max_zone=11, temp_min_f=55, temp_max_f=90,
    soil_ph_min=6.0, soil_ph_max=6.8, soil_type='Well-draining sandy loam',
    good_neighbors=['Basil','Carrot','Tomato','Marigold'],
    bad_neighbors=['Fennel','Brassicas'],
    sow_indoor_weeks=10, direct_sow_offset=None, transplant_offset=2,
    how_to_grow=dict(
        starting='Start indoors 10–12 weeks before last frost at 80–85°F. Germination takes 10–21 days; use a heat mat.',
        seedling='Grow at 70°F+ under bright light. Pinch first buds to encourage branching.',
        vegetative='Transplant to full sun after last frost. Consistent moisture is key; water stress increases heat level.',
        flowering='Self-pollinating. Avoid nitrogen-heavy fertilizer once flowers appear.',
        harvest='Pick dark green for milder heat, red for maximum heat. Wear gloves when harvesting.',
    ),
    faqs=[
        dict(q='How do I make jalapeños hotter?', a='Stress the plant slightly — reduce watering during ripening. Heat level increases as the pepper matures to red.'),
        dict(q='Why do my jalapeños have brown lines (corking)?', a='Corking (stretch marks) is a sign of rapid growth and is normal. It often indicates a hotter, more mature pepper.'),
        dict(q='Can I grow jalapeños in pots?', a='Yes — a 3-gallon pot per plant works well. They make attractive patio plants.'),
    ],
    nutrition=dict(serving_size='1 pepper (14g)', calories=4, protein_g=0.1, carbs_g=0.9, fiber_g=0.4, fat_g=0.05,
        vitamins=['Vitamin C: 10% DV','Vitamin A: 2% DV'],
        notes='Capsaicin, the compound that causes heat, has anti-inflammatory properties and may boost metabolism.'),
),
'Cucumber': dict(
    difficulty='Easy', min_zone=4, max_zone=11, temp_min_f=60, temp_max_f=95,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Rich, well-draining loam with high organic matter',
    good_neighbors=['Bean','Corn','Pea','Sunflower','Radish','Marigold'],
    bad_neighbors=['Potato','Sage','Fennel','Mint'],
    sow_indoor_weeks=4, direct_sow_offset=2, transplant_offset=2,
    how_to_grow=dict(
        starting='Direct sow after last frost is preferred — cucumbers dislike root disturbance. Or start indoors 3–4 weeks early in biodegradable pots.',
        seedling='Thin to one plant per 12". Keep soil warm (65°F+). Cucumbers grow fast once established.',
        vegetative='Provide a trellis for vining types. Water deeply 1× per week. Side-dress with compost when vines start running.',
        flowering='Male flowers appear first, then females (with tiny cucumber at base). Bees needed for pollination. Plant bee-friendly flowers nearby.',
        harvest='Harvest frequently (every 2 days) to keep plant producing. Pick slicers at 6–8", picklers at 2–4". Yellowing means overripe.',
    ),
    faqs=[
        dict(q='Why are my cucumbers bitter?', a='Bitterness is caused by heat stress, irregular watering, or leaving cucumbers on the vine too long. Water consistently and harvest promptly.'),
        dict(q='Why do my female flowers fall off without fruiting?', a='No pollination. Attract bees by planting flowers nearby, or hand-pollinate with a small brush.'),
        dict(q='Can cucumbers grow vertically?', a='Yes — trellising saves space, improves airflow, and produces straighter fruit. Any sturdy 5–6-foot support works.'),
    ],
    nutrition=dict(serving_size='½ cup slices (52g)', calories=8, protein_g=0.3, carbs_g=1.9, fiber_g=0.3, fat_g=0.1,
        vitamins=['Vitamin K: 9% DV','Vitamin C: 2% DV','Potassium: 3% DV'],
        notes='Cucumbers are 96% water, making them excellent for hydration. Leave the skin on for extra fiber and vitamins.'),
),
'Zucchini': dict(
    difficulty='Easy', min_zone=3, max_zone=11, temp_min_f=60, temp_max_f=95,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Rich, well-draining loam',
    good_neighbors=['Bean','Corn','Pea','Nasturtium','Marigold'],
    bad_neighbors=['Potato','Fennel'],
    sow_indoor_weeks=3, direct_sow_offset=2, transplant_offset=2,
    how_to_grow=dict(
        starting='Direct sow 2 weeks after last frost is ideal. Or start indoors 3 weeks early in large pots to minimize transplant shock.',
        seedling='Thin to one plant per hill. Zucchini grows very quickly — expect rapid expansion once established.',
        vegetative='Needs full sun and plenty of space (3×3 ft per plant). Water at base to prevent powdery mildew. Feed every 2 weeks.',
        flowering='Large yellow flowers are edible. Male flowers appear before females. Hand-pollinate if bees are scarce.',
        harvest='Harvest at 6–8" for best flavor. Zucchini left on plant grow rapidly — check daily. Oversized fruit is seedy and watery.',
    ),
    faqs=[
        dict(q='Why do my zucchini rot at the blossom end?', a='Blossom end rot or failed pollination. The female flower must be pollinated within a day of opening. Bring in hand-pollination if bee activity is low.'),
        dict(q='How do I prevent powdery mildew on zucchini?', a='Water at the base (not overhead), space plants well, and apply a baking soda spray (1 tsp per quart water) at first sign.'),
        dict(q='One plant produced too much — what do I do?', a="Zucchini is prolific. Share with neighbors, freeze grated zucchini, or make zucchini bread. Plant just 1–2 plants unless you have a big family."),
    ],
    nutrition=dict(serving_size='1 cup sliced (124g)', calories=20, protein_g=1.5, carbs_g=3.6, fiber_g=1.1, fat_g=0.4,
        vitamins=['Vitamin C: 35% DV','Vitamin B6: 12% DV','Manganese: 10% DV','Potassium: 9% DV'],
        notes='Low in calories and high in water content. The skin is rich in antioxidants — leave it on when cooking.'),
),
'Pumpkin': dict(
    difficulty='Easy', min_zone=3, max_zone=11, temp_min_f=65, temp_max_f=95,
    soil_ph_min=6.0, soil_ph_max=6.8, soil_type='Rich, deep, well-draining loam',
    good_neighbors=['Corn','Bean','Nasturtium','Marigold'],
    bad_neighbors=['Potato','Fennel','Brassicas'],
    sow_indoor_weeks=3, direct_sow_offset=2, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow 2 weeks after last frost in hills of 2–3 seeds. Thin to strongest 1–2 plants. Or start 3 weeks early indoors.',
        seedling='Germination is fast (5–10 days) in warm soil. Seedlings grow rapidly; ensure plenty of space before planting.',
        vegetative='Pumpkins need 6–8 ft of running room. Water deeply at roots. Lay vines carefully as they run.',
        flowering='Male flowers appear 1–2 weeks before females. Hand-pollinate in the morning for best fruit set.',
        harvest='Harvest when shell is hard, color is deep, and the stem begins to dry and cork. Cut with 3–4" of stem. Cure in sun 1–2 weeks.',
    ),
    faqs=[
        dict(q='How much space does a pumpkin need?', a='Standard varieties need 50–100 sq ft per plant. Bush types need about 25 sq ft. Miniature varieties are suitable for small gardens.'),
        dict(q='Why are my pumpkins turning orange early?', a='Stress from drought, disease, or root damage can cause premature color change. Ensure consistent watering and healthy vines.'),
        dict(q='Can I grow pumpkins vertically?', a='Small/miniature varieties can be trellised. Large varieties are too heavy and must grow along the ground.'),
    ],
    nutrition=dict(serving_size='1 cup cooked (245g)', calories=49, protein_g=2.0, carbs_g=12.0, fiber_g=2.7, fat_g=0.2,
        vitamins=['Vitamin A: 245% DV','Vitamin C: 19% DV','Potassium: 16% DV','Vitamin E: 10% DV'],
        notes='Exceptionally rich in beta-carotene (vitamin A). Pumpkin seeds are high in magnesium, zinc, and healthy fats.'),
),
'Corn': dict(
    difficulty='Moderate', min_zone=3, max_zone=11, temp_min_f=60, temp_max_f=95,
    soil_ph_min=5.8, soil_ph_max=7.0, soil_type='Deep, fertile, well-draining loam',
    good_neighbors=['Bean','Squash','Cucumber','Pumpkin','Melon'],
    bad_neighbors=['Tomato','Celery'],
    sow_indoor_weeks=None, direct_sow_offset=2, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow only — corn dislikes transplanting. Sow 1" deep after last frost when soil is 60°F+. Plant in blocks of 4+ rows for wind pollination.',
        seedling='Thin to 12" apart. Keep weed-free while young. Corn is a heavy feeder; side-dress with nitrogen at knee-height.',
        vegetative='Grows rapidly in warm weather. Water deeply 1× per week. Avoid overhead watering once tassels form.',
        flowering='Tassels release pollen that falls onto silks. Each silk becomes one kernel. Plant in blocks, not single rows, to ensure pollination.',
        harvest='Harvest 18–24 days after silk appears. Peel back husk — kernels should be plump and milky. Cook or refrigerate immediately for best sweetness.',
    ),
    faqs=[
        dict(q='Why is my corn not producing ears?', a='Likely a pollination problem. Corn is wind-pollinated and needs to be planted in blocks of at least 4 rows. Single rows often fail to pollinate.'),
        dict(q='How do I control corn earworm?', a='Apply a drop of mineral oil to the silk 3–7 days after silks emerge. Bt (Bacillus thuringiensis) spray is also effective.'),
        dict(q='When is corn ready to harvest?', a='About 20 days after silks appear. The silks will be brown and dry. Press a kernel — milky juice means it\'s ready; clear means too early; pasty means overripe.'),
    ],
    nutrition=dict(serving_size='1 medium ear (90g)', calories=77, protein_g=2.9, carbs_g=17.1, fiber_g=1.9, fat_g=1.1,
        vitamins=['Thiamine (B1): 13% DV','Folate: 11% DV','Magnesium: 9% DV','Phosphorus: 10% DV'],
        notes='Sweet corn is high in lutein and zeaxanthin, antioxidants that support eye health.'),
),
'Green Bean': dict(
    difficulty='Easy', min_zone=3, max_zone=11, temp_min_f=60, temp_max_f=90,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Light, well-draining loam',
    good_neighbors=['Carrot','Cucumber','Corn','Strawberry','Radish'],
    bad_neighbors=['Onion','Garlic','Fennel','Beet'],
    sow_indoor_weeks=None, direct_sow_offset=2, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow 1–2 weeks after last frost, 1" deep, 3" apart. Beans dislike root disturbance so avoid transplanting.',
        seedling='Germination in 7–14 days. Keep soil moist until established. Thin bush beans to 6", pole beans to 6–8".',
        vegetative='Bush beans need no support. Pole beans need a trellis 4–6 ft tall. Inoculate seeds with rhizobium bacteria for better nitrogen fixation.',
        flowering='White or purple flowers self-pollinate. Avoid disturbing plants when wet to prevent disease spread.',
        harvest='Pick pods when they snap cleanly, before seeds inside bulge visibly. Harvest every 2–3 days to keep plants producing.',
    ),
    faqs=[
        dict(q='Bush beans vs pole beans — which is better?', a='Bush beans mature faster and all at once (good for preserving). Pole beans produce over a longer period and yield more per plant but need support.'),
        dict(q='Why are my bean pods tough and stringy?', a='Beans that are left on the vine too long become fibrous. Harvest promptly while pods are still slender.'),
        dict(q='Do beans need fertilizer?', a='Beans fix their own nitrogen so heavy feeding is unnecessary. Excess nitrogen causes leafy growth at the expense of pods.'),
    ],
    nutrition=dict(serving_size='1 cup cooked (125g)', calories=44, protein_g=2.4, carbs_g=9.9, fiber_g=4.0, fat_g=0.4,
        vitamins=['Vitamin C: 18% DV','Vitamin K: 22% DV','Folate: 10% DV','Manganese: 14% DV'],
        notes='A good source of plant protein and fiber. Green beans also contain silicon, which supports bone and connective tissue health.'),
),
'Pea': dict(
    difficulty='Easy', min_zone=2, max_zone=11, temp_min_f=35, temp_max_f=75,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Well-draining loam, cool and moist',
    good_neighbors=['Carrot','Radish','Turnip','Lettuce','Cucumber','Corn'],
    bad_neighbors=['Onion','Garlic','Leek','Shallot'],
    sow_indoor_weeks=None, direct_sow_offset=-6, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow 4–6 weeks before last frost. Peas prefer cool weather and will bolt in heat. Sow 1" deep, 2" apart.',
        seedling='Germination in 7–14 days. Thin to 4" for bush types. Install trellis at planting for climbing varieties.',
        vegetative='Cool-season crop — grows best below 70°F. Water consistently but avoid waterlogging. Inoculate with pea/bean rhizobium.',
        flowering='Delicate white or purple flowers self-pollinate. Avoid heat — peas stop setting pods above 80°F.',
        harvest='Pick sugar snaps when pods are plump and round. Pick snow peas before seeds develop. Check daily once pods appear.',
    ),
    faqs=[
        dict(q='Why did my peas stop producing in summer?', a='Peas are cool-season crops and go dormant or die in heat above 80°F. Plant a second crop in late summer for a fall harvest.'),
        dict(q='Do peas need a trellis?', a='Bush peas can stand on their own (2–3 ft). Climbing/vining types (4–6 ft) need a trellis, fence, or pea sticks.'),
        dict(q='Can I eat the pea shoots and tendrils?', a='Yes! Pea shoots and young tendrils are delicious raw in salads or stir-fried. Harvest regularly from the top 2–3 inches.'),
    ],
    nutrition=dict(serving_size='½ cup cooked (80g)', calories=62, protein_g=4.1, carbs_g=11.4, fiber_g=4.4, fat_g=0.2,
        vitamins=['Vitamin C: 16% DV','Vitamin K: 24% DV','Thiamine: 22% DV','Folate: 12% DV'],
        notes='One of the best plant protein sources among vegetables. Rich in B vitamins and fiber.'),
),
'Lettuce': dict(
    difficulty='Easy', min_zone=2, max_zone=11, temp_min_f=35, temp_max_f=75,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Moist, fertile loam; good drainage',
    good_neighbors=['Carrot','Radish','Strawberry','Onion','Chives','Cucumber'],
    bad_neighbors=['Fennel','Celery'],
    sow_indoor_weeks=4, direct_sow_offset=-4, transplant_offset=-2,
    how_to_grow=dict(
        starting='Direct sow outdoors 4–6 weeks before last frost, or start indoors for transplanting. Seeds need light to germinate — press into surface, do not bury.',
        seedling='Thin to 6–10" depending on variety. Lettuce is shallow-rooted and needs consistent moisture. Grows quickly in cool weather.',
        vegetative='Cool-season crop. Provide partial shade in warm climates to extend season. Succession plant every 2–3 weeks for continuous harvest.',
        flowering='Bolting (going to flower) is triggered by heat and long days. Leaves become bitter. Pull plants when center stalk appears.',
        harvest='Harvest outer leaves for cut-and-come-again, or pull whole heads. Best in morning when crisp. Refrigerate immediately.',
    ),
    faqs=[
        dict(q='Why does my lettuce taste bitter?', a='Bitterness indicates heat stress or bolting. Harvest before the central stalk appears and provide shade in warm weather.'),
        dict(q='Can I grow lettuce in containers?', a='Yes — lettuce is ideal for containers and window boxes. A 6" depth is sufficient. Grows well indoors on a sunny windowsill.'),
        dict(q='How do I do cut-and-come-again harvesting?', a='Harvest outer leaves leaving the growing center intact. The plant will continue producing. Works best with loose-leaf varieties.'),
    ],
    nutrition=dict(serving_size='2 cups shredded (85g)', calories=14, protein_g=1.3, carbs_g=2.5, fiber_g=1.3, fat_g=0.2,
        vitamins=['Vitamin A: 148% DV (romaine)','Vitamin K: 96% DV','Vitamin C: 18% DV','Folate: 16% DV'],
        notes='Romaine is significantly more nutritious than iceberg. Darker greens have higher vitamin and antioxidant content.'),
),
'Spinach': dict(
    difficulty='Easy', min_zone=2, max_zone=11, temp_min_f=35, temp_max_f=75,
    soil_ph_min=6.5, soil_ph_max=7.5, soil_type='Rich, moist loam with good drainage',
    good_neighbors=['Strawberry','Radish','Pea','Onion','Garlic'],
    bad_neighbors=['Fennel'],
    sow_indoor_weeks=None, direct_sow_offset=-6, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow 6–8 weeks before last frost, ½" deep, 2" apart. Can germinate in soil as cold as 35°F.',
        seedling='Thin to 4–6". Water regularly. Mulch to keep roots cool and moisture even.',
        vegetative='Grows best below 65°F. Provide full sun in spring/fall, partial shade in warmer periods. Fertilize lightly with nitrogen.',
        flowering='Bolts quickly in long summer days. Leaves become small and pointed before bolting. Succession plant for continuous supply.',
        harvest='Harvest outer leaves continuously, or cut whole plant 2" above soil for regrowth. Best before the center stalk elongates.',
    ),
    faqs=[
        dict(q='Why does my spinach keep bolting?', a='Bolting is triggered by day length (over 14 hours) and heat. Choose bolt-resistant varieties and plant in early spring or fall.'),
        dict(q='Can I freeze spinach from my garden?', a='Yes — blanch for 2 minutes, cool in ice water, squeeze dry, then freeze in portions. Great for smoothies and cooked dishes.'),
        dict(q='Is spinach the most nutritious green?', a='It is among the most nutrient-dense greens, especially in iron, folate, and vitamins K and A. However, oxalic acid reduces iron absorption — pair with vitamin C.'),
    ],
    nutrition=dict(serving_size='1 cup raw (30g)', calories=7, protein_g=0.9, carbs_g=1.1, fiber_g=0.7, fat_g=0.1,
        vitamins=['Vitamin K: 121% DV','Vitamin A: 56% DV','Folate: 15% DV','Iron: 5% DV','Vitamin C: 14% DV'],
        notes='One of the most nutrient-dense foods available. Cooking concentrates nutrients but reduces volume dramatically (10 oz raw = ~1 cup cooked).'),
),
'Kale': dict(
    difficulty='Easy', min_zone=2, max_zone=11, temp_min_f=20, temp_max_f=80,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Rich, well-draining loam',
    good_neighbors=['Beet','Celery','Cucumber','Herb','Onion'],
    bad_neighbors=['Tomato','Strawberry','Bean','Pole Bean'],
    sow_indoor_weeks=6, direct_sow_offset=-4, transplant_offset=-2,
    how_to_grow=dict(
        starting='Start indoors 6 weeks before last frost or direct sow 4 weeks before. Sow ¼" deep. Can also be sown in summer for fall harvest.',
        seedling='Thin to 12–18" apart. Kale seedlings are robust and transplant well.',
        vegetative='Full sun preferred but tolerates partial shade. Water consistently. Frost actually sweetens kale leaves.',
        flowering='Kale left through winter will bolt in spring. Flowering stalks are edible — eat like broccoli raab.',
        harvest='Harvest outer leaves, leaving the central growing point. Pick from the bottom up. Young inner leaves are most tender.',
    ),
    faqs=[
        dict(q='Does kale get sweeter after frost?', a='Yes — frost converts starches to sugars, significantly sweetening the leaves. Fall and winter kale is often the best-tasting.'),
        dict(q='Why are my kale leaves tough?', a='Tough leaves are usually older, outer leaves. The inner leaves are more tender. Massage raw kale with a little oil and salt to break down fibers for salads.'),
        dict(q='How do I control cabbage worms on kale?', a='Row covers are the most effective prevention. Bt (Bacillus thuringiensis) spray kills caterpillars organically. Hand-pick eggs from leaf undersides.'),
    ],
    nutrition=dict(serving_size='1 cup raw (21g)', calories=7, protein_g=0.9, carbs_g=1.0, fiber_g=0.6, fat_g=0.3,
        vitamins=['Vitamin K: 68% DV','Vitamin A: 6% DV','Vitamin C: 22% DV','Calcium: 9% DV'],
        notes='A nutritional powerhouse. Kale contains quercetin and kaempferol, antioxidants with anti-inflammatory and heart-protective effects.'),
),
'Swiss Chard': dict(
    difficulty='Easy', min_zone=3, max_zone=11, temp_min_f=35, temp_max_f=90,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Rich, moist, well-draining loam',
    good_neighbors=['Bean','Onion','Garlic','Cabbage'],
    bad_neighbors=['Corn','Cucumber','Squash'],
    sow_indoor_weeks=4, direct_sow_offset=-2, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow 2–4 weeks before last frost, or start indoors 4 weeks early. Each "seed" is actually a cluster; thin early.',
        seedling='Thin to 6–12". Swiss chard transplants easily and recovers quickly.',
        vegetative='Tolerates heat better than most cool-season greens. Water consistently. Grows in partial shade.',
        flowering='Bolting is rare in chard but occurs in extreme heat. Cut flower stalks to prolong leaf harvest.',
        harvest='Cut outer stalks at base when 8–10" long. Plant regrows from center. Full plant can be cut 2" above soil and will regrow.',
    ),
    faqs=[
        dict(q='Are rainbow chard stems edible?', a='Yes — the stems are tender and flavorful, though they take longer to cook than the leaves. Chop and add to the pan 2–3 minutes before the leaves.'),
        dict(q='Can I eat Swiss chard raw?', a='Yes, young leaves are excellent in salads. Mature leaves are better cooked as they can be slightly bitter and chewy raw.'),
    ],
    nutrition=dict(serving_size='1 cup cooked (175g)', calories=35, protein_g=3.3, carbs_g=7.2, fiber_g=3.7, fat_g=0.1,
        vitamins=['Vitamin K: 636% DV','Vitamin A: 60% DV','Vitamin C: 53% DV','Magnesium: 38% DV'],
        notes='Exceptionally high in vitamin K. Contains betalains (the same pigments as beets) which have antioxidant properties.'),
),
'Broccoli': dict(
    difficulty='Moderate', min_zone=2, max_zone=11, temp_min_f=30, temp_max_f=75,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Rich, firm, well-draining loam',
    good_neighbors=['Beet','Celery','Onion','Potato','Sage','Dill'],
    bad_neighbors=['Tomato','Strawberry','Pepper','Bean','Corn'],
    sow_indoor_weeks=8, direct_sow_offset=-4, transplant_offset=-4,
    how_to_grow=dict(
        starting='Start indoors 6–8 weeks before last spring frost or 10 weeks before first fall frost. Sow ¼" deep at 65–75°F.',
        seedling='Transplant when 4–6" tall. Harden off well. Broccoli tolerates light frost and prefers cool temps.',
        vegetative='Full sun. Consistent moisture. Side-dress with nitrogen when plants are 6" tall. Protect from cabbage worms with row covers.',
        flowering='The "head" is actually a mass of flower buds. Harvest before any yellow color appears — that means flowers are opening.',
        harvest='Cut main head with 5–6" of stem. Side shoots will continue to produce for weeks after main head harvest.',
    ),
    faqs=[
        dict(q='Why did my broccoli head turn yellow?', a='Yellow flowers mean the head has begun to bolt, usually due to heat or waiting too long. Harvest as soon as heads reach full size before any yellowing starts.'),
        dict(q='Can I eat broccoli leaves?', a='Yes — broccoli leaves are nutritious and taste similar to kale. Use young leaves raw or cook older leaves like collards.'),
        dict(q='Why is my broccoli producing tiny scattered heads?', a='Premature "buttoning" is caused by heat, cold stress, or transplant shock while plants were too young. Avoid planting too early or too late.'),
    ],
    nutrition=dict(serving_size='1 cup chopped (91g)', calories=31, protein_g=2.5, carbs_g=6.0, fiber_g=2.4, fat_g=0.3,
        vitamins=['Vitamin C: 135% DV','Vitamin K: 116% DV','Folate: 14% DV','Vitamin A: 11% DV'],
        notes='Contains sulforaphane, a compound with strong cancer-fighting and anti-inflammatory properties that is most active when broccoli is eaten raw or lightly cooked.'),
),
'Cauliflower': dict(
    difficulty='Challenging', min_zone=2, max_zone=11, temp_min_f=35, temp_max_f=75,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Rich, moist, well-draining loam',
    good_neighbors=['Celery','Onion','Sage','Dill','Beet'],
    bad_neighbors=['Tomato','Strawberry','Pepper'],
    sow_indoor_weeks=8, direct_sow_offset=None, transplant_offset=-4,
    how_to_grow=dict(
        starting='Start indoors 6–8 weeks before last frost. Cauliflower is temperature-sensitive and dislikes both frost and heat.',
        seedling='Handle carefully — cauliflower hates root disturbance. Harden off thoroughly. Transplant at 6" height.',
        vegetative='Needs consistent moisture and nutrients. Fluctuating temps cause poor head formation. Protect from pests with row covers.',
        flowering='When heads are golf ball-sized, "blanch" by tying outer leaves over the head to keep it white and sweet.',
        harvest='Harvest when head is firm, compact, and white (6–8" diameter). Don\'t wait — it deteriorates quickly after maturity.',
    ),
    faqs=[
        dict(q='Why is my cauliflower head purple or brown?', a='Purple tinge is harmless (exposure to sunlight or cold). Brown spots indicate disease or over-maturity. Blanch with leaves tied over to keep white.'),
        dict(q='Why did my cauliflower produce a small, loose head?', a='Temperature stress (too warm or too cold at heading time) causes poor curd formation. Cauliflower has a narrow temperature window of 60–70°F for heading.'),
        dict(q='Do I have to blanch cauliflower?', a='Traditional white varieties need blanching. Colored varieties (purple, orange, green Romanesco) do not need blanching.'),
    ],
    nutrition=dict(serving_size='1 cup raw (107g)', calories=27, protein_g=2.1, carbs_g=5.3, fiber_g=2.1, fat_g=0.3,
        vitamins=['Vitamin C: 77% DV','Vitamin K: 20% DV','Folate: 15% DV','Vitamin B6: 12% DV'],
        notes='Contains choline, an essential nutrient for brain health. Rich in glucosinolates that convert to cancer-fighting compounds.'),
),
'Cabbage': dict(
    difficulty='Moderate', min_zone=1, max_zone=11, temp_min_f=25, temp_max_f=75,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Rich, firm, moist loam',
    good_neighbors=['Dill','Sage','Celery','Onion','Potato'],
    bad_neighbors=['Tomato','Strawberry','Bean','Grape'],
    sow_indoor_weeks=8, direct_sow_offset=-4, transplant_offset=-4,
    how_to_grow=dict(
        starting='Start indoors 6–8 weeks before last frost. Direct sow in garden 4 weeks before last frost for fall crops.',
        seedling='Harden off thoroughly before transplanting. Cabbage tolerates frost well once established.',
        vegetative='Water consistently. Mulch to retain moisture. Side-dress with nitrogen. Use row covers to exclude cabbage moths.',
        flowering='Cabbage heads that crack are ready or overripe. If weather is wet after dry spell, heads may split.',
        harvest='Heads are ready when firm and dense when squeezed. Cut just above the base. Leave root to grow small secondary heads.',
    ),
    faqs=[
        dict(q='Why did my cabbage split?', a='Rapid uptake of water after dry spell causes the interior to outgrow the outer leaves. Harvest promptly when heads feel firm, and keep watering consistent.'),
        dict(q='How do I stop cabbage worms?', a='Cover with floating row covers, use Bt spray, or hand-pick. Check undersides of leaves for yellow egg clusters and remove them.'),
    ],
    nutrition=dict(serving_size='1 cup shredded (89g)', calories=22, protein_g=1.1, carbs_g=5.2, fiber_g=2.2, fat_g=0.1,
        vitamins=['Vitamin C: 54% DV','Vitamin K: 85% DV','Vitamin B6: 8% DV','Folate: 10% DV'],
        notes='Fermented cabbage (sauerkraut, kimchi) is rich in probiotics. Red cabbage contains anthocyanins, potent antioxidants.'),
),
'Carrot': dict(
    difficulty='Moderate', min_zone=2, max_zone=11, temp_min_f=45, temp_max_f=80,
    soil_ph_min=6.0, soil_ph_max=6.8, soil_type='Deep, loose, sandy loam; free of rocks and clumps',
    good_neighbors=['Lettuce','Onion','Leek','Rosemary','Sage','Tomato'],
    bad_neighbors=['Dill','Fennel','Parsnip'],
    sow_indoor_weeks=None, direct_sow_offset=-4, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow only — carrots are tap-rooted and cannot be transplanted. Sow thinly ¼" deep in loose soil 4 weeks before last frost.',
        seedling='Germination is slow (14–21 days). Keep soil moist. Thin to 2–3" apart once 1" tall. Competition stunts roots.',
        vegetative='Deep, loose, stone-free soil is essential. Add sand to clay soils. Side-dress with potassium (not nitrogen, which causes hairy roots).',
        flowering='Carrots left in the ground in spring will bolt. The flower clusters (umbels) attract beneficial insects.',
        harvest='Harvest 60–80 days after sowing. Pull a test carrot — shoulders should be ¾–1" wide. Frost sweetens carrots significantly.',
    ),
    faqs=[
        dict(q='Why are my carrots forked or twisted?', a='Forking is caused by rocks, clumps, fresh manure, or overcrowding. Prepare a deep, loose, stone-free bed and thin properly.'),
        dict(q='Why are my carrots all top and no root?', a='Too much nitrogen (from fresh manure or high-N fertilizer) causes leafy tops at the expense of root growth.'),
        dict(q='Can I leave carrots in the ground over winter?', a='Yes in zones 6+ — mulch heavily and harvest as needed. Frost makes them sweeter. In colder zones, harvest before hard freeze.'),
    ],
    nutrition=dict(serving_size='1 medium carrot (61g)', calories=25, protein_g=0.6, carbs_g=5.8, fiber_g=1.7, fat_g=0.1,
        vitamins=['Vitamin A: 204% DV','Vitamin K: 16% DV','Potassium: 6% DV','Vitamin C: 6% DV'],
        notes='Extremely rich in beta-carotene, which the body converts to vitamin A. Cooking with a little fat increases beta-carotene absorption by 3–4×.'),
),
'Radish': dict(
    difficulty='Easy', min_zone=2, max_zone=11, temp_min_f=40, temp_max_f=75,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Loose, well-draining loam',
    good_neighbors=['Carrot','Lettuce','Pea','Cucumber','Spinach'],
    bad_neighbors=['Hyssop','Agastache'],
    sow_indoor_weeks=None, direct_sow_offset=-4, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow ½" deep, 1" apart, 4–6 weeks before last frost. Radishes are the fastest garden vegetable.',
        seedling='Thin to 2" apart after germination (3–5 days). Keep soil moist.',
        vegetative='Cool-season only. Bolts in heat. Succession plant every 10 days for continuous harvest.',
        flowering='Bolting makes roots woody and bitter. Flowers and seed pods are edible.',
        harvest='Spring radishes ready in 20–30 days. Pull when roots are ¾–1" in diameter. Don\'t wait — they become hollow and hot.',
    ),
    faqs=[
        dict(q='Why are my radishes all top and no root?', a='Caused by: too much nitrogen, poor thinning, or too much shade. Ensure 6+ hours of sun and thin aggressively.'),
        dict(q='Why are my radishes hollow?', a='Left too long in the ground. Radishes should be harvested promptly once they reach size.'),
    ],
    nutrition=dict(serving_size='1 cup sliced (116g)', calories=19, protein_g=0.8, carbs_g=3.9, fiber_g=1.9, fat_g=0.1,
        vitamins=['Vitamin C: 29% DV','Folate: 7% DV','Potassium: 7% DV'],
        notes='Radishes are a liver-supporting food that may help detoxification. The greens are also edible and nutritious.'),
),
'Beet': dict(
    difficulty='Easy', min_zone=2, max_zone=11, temp_min_f=40, temp_max_f=85,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Loose, well-draining loam; tolerates clay better than carrots',
    good_neighbors=['Onion','Garlic','Lettuce','Kohlrabi','Brassicas'],
    bad_neighbors=['Bean','Field Mustard','Charlock'],
    sow_indoor_weeks=None, direct_sow_offset=-4, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow ½–1" deep, 1" apart, 4–6 weeks before last frost. Each seed cluster produces 2–4 seedlings.',
        seedling='Thin to 3–4" apart, eating thinnings as beet greens. Both root and greens are edible from day one.',
        vegetative='Tolerates light frost well. Water consistently to prevent rings in the root. Side-dress with boron-containing fertilizer if needed.',
        flowering='Second-year crop (biennial). Bolting in heat makes roots woody. Harvest before.',
        harvest='Pull when 1.5–3" in diameter. Smaller beets are more tender. Twist off greens 1" above root to prevent bleeding.',
    ),
    faqs=[
        dict(q='Can I eat beet greens?', a='Yes — beet greens are one of the most nutritious parts of the plant, similar to Swiss chard. Use young greens raw in salads; cook older leaves.'),
        dict(q='Why is my urine pink after eating beets?', a='Beeturia is harmless. Betalain pigments from beets can color urine and stools pink/red. It is more common in people with low stomach acid.'),
    ],
    nutrition=dict(serving_size='1 cup cooked (170g)', calories=75, protein_g=2.9, carbs_g=17.0, fiber_g=3.4, fat_g=0.3,
        vitamins=['Folate: 34% DV','Manganese: 22% DV','Potassium: 11% DV','Vitamin C: 11% DV'],
        notes='Beets are high in dietary nitrates that improve blood flow and exercise performance. The betalain pigments are powerful antioxidants.'),
),
'Onion': dict(
    difficulty='Moderate', min_zone=2, max_zone=11, temp_min_f=35, temp_max_f=85,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Rich, well-draining loam; high organic matter',
    good_neighbors=['Carrot','Beet','Lettuce','Tomato','Pepper','Chamomile'],
    bad_neighbors=['Bean','Pea','Asparagus','Sage'],
    sow_indoor_weeks=12, direct_sow_offset=-6, transplant_offset=-4,
    how_to_grow=dict(
        starting='Start indoors 10–12 weeks before last frost, or use sets (small bulbs) for easier growing. Sow ¼" deep.',
        seedling='Keep moist. Clip tops to 3" to encourage bulb development. Harden off thoroughly.',
        vegetative='Full sun essential. Loosen soil around bulbs as they swell. Stop watering when tops begin to fall over.',
        flowering='Flowering (bolting) means the bulb will stop developing. Remove flower heads to preserve bulb size.',
        harvest='Harvest when tops fall over and turn brown. Cure in warm, airy place 2–4 weeks before storing.',
    ),
    faqs=[
        dict(q='When do I know onions are ready?', a='When about half the tops have fallen over naturally, bend the rest flat. Allow to cure in the field for a week, then move to a warm, airy space for 2–4 weeks.'),
        dict(q='What causes small onions?', a='Day length determines bulbing. Short-day varieties for southern zones, long-day for northern zones. Using the wrong type for your zone causes small, unsatisfying bulbs.'),
    ],
    nutrition=dict(serving_size='1 medium onion (110g)', calories=44, protein_g=1.2, carbs_g=10.3, fiber_g=1.9, fat_g=0.1,
        vitamins=['Vitamin C: 18% DV','Vitamin B6: 12% DV','Folate: 5% DV','Potassium: 5% DV'],
        notes='Rich in quercetin, an antioxidant with anti-inflammatory properties. Cooking reduces quercetin content — raw onion is most potent.'),
),
'Garlic': dict(
    difficulty='Easy', min_zone=2, max_zone=9, temp_min_f=25, temp_max_f=85,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Rich, well-draining loam; no waterlogging',
    good_neighbors=['Tomato','Carrot','Beet','Rose','Fruit trees'],
    bad_neighbors=['Bean','Pea','Asparagus'],
    sow_indoor_weeks=None, direct_sow_offset=-20, transplant_offset=None,
    how_to_grow=dict(
        starting='Plant individual cloves (pointed end up) 2" deep in fall, 4–6 weeks before hard freeze. Mulch heavily with straw.',
        seedling='Shoots emerge in spring. The cold winter period is necessary for bulb development.',
        vegetative='Remove any flower scapes (curled tops on hardneck varieties) — the scapes are edible and diverting energy away helps bulb growth.',
        flowering='Softneck garlic rarely flowers. Hardneck varieties send up scapes in early summer — harvest scapes when curled.',
        harvest='Harvest when lower 3–4 leaves have died (typically June–July). Cure in a warm, airy, shaded spot for 3–4 weeks.',
    ),
    faqs=[
        dict(q='Can I plant garlic in spring?', a='Spring-planted garlic produces much smaller bulbs since it misses the cold vernalization period. Fall planting is strongly recommended in most climates.'),
        dict(q='What is the difference between hardneck and softneck garlic?', a='Hardneck varieties have better flavor and complexity, produce scapes, and store 3–6 months. Softneck stores up to a year and is what you find in grocery stores.'),
        dict(q='Why are my garlic cloves small?', a='May be planted too shallowly, too close together (space 6"), or scapes were not removed. Ensure fertile soil and remove scapes promptly.'),
    ],
    nutrition=dict(serving_size='3 cloves (9g)', calories=13, protein_g=0.6, carbs_g=3.0, fiber_g=0.2, fat_g=0.1,
        vitamins=['Vitamin C: 5% DV','Vitamin B6: 5% DV','Manganese: 8% DV'],
        notes='Allicin, formed when garlic is chopped or crushed, has potent antimicrobial and cardiovascular benefits. Let garlic rest 10 minutes after chopping before cooking for maximum allicin formation.'),
),
'Arugula': dict(
    difficulty='Easy', min_zone=2, max_zone=11, temp_min_f=35, temp_max_f=70,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Well-draining loam; tolerates poorer soils',
    good_neighbors=['Lettuce','Spinach','Carrot','Onion'],
    bad_neighbors=['Fennel'],
    sow_indoor_weeks=None, direct_sow_offset=-4, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow ¼" deep in early spring or fall. One of the fastest-growing salad greens.',
        seedling='Thin to 4–6". Arugula needs little care and grows well in average soil.',
        vegetative='Succession sow every 2–3 weeks. Best in cool weather — bolts quickly in summer.',
        flowering='Flowers are edible with a mild peppery flavor. White flowers indicate bolting; leaves become very spicy.',
        harvest='Begin harvesting outer leaves at 3–4 weeks. Cut-and-come-again works well until plants bolt.',
    ),
    faqs=[
        dict(q='Why is my arugula too spicy?', a='Spiciness increases with heat and bolting. Grow in cool seasons and harvest young leaves for milder flavor.'),
        dict(q='Can I grow arugula year-round?', a='In mild climates yes. In cold climates: spring + fall crops. It survives light frost and grows under row covers in winter.'),
    ],
    nutrition=dict(serving_size='2 cups (40g)', calories=10, protein_g=1.0, carbs_g=1.5, fiber_g=0.6, fat_g=0.3,
        vitamins=['Vitamin K: 43% DV','Vitamin A: 12% DV','Folate: 10% DV','Vitamin C: 8% DV'],
        notes='Rich in glucosinolates, compounds with potential cancer-protective properties. The peppery flavor comes from these same compounds.'),
),
'Asparagus': dict(
    difficulty='Challenging', min_zone=3, max_zone=8, temp_min_f=25, temp_max_f=85,
    soil_ph_min=6.5, soil_ph_max=7.5, soil_type='Deep, well-draining sandy loam; enriched with compost',
    good_neighbors=['Tomato','Parsley','Basil','Marigold'],
    bad_neighbors=['Onion','Garlic','Potato'],
    sow_indoor_weeks=None, direct_sow_offset=None, transplant_offset=0,
    how_to_grow=dict(
        starting='Plant 1-year-old crowns (not seeds) in spring in a permanent trench 8–12" deep with compost. Asparagus is a perennial — choose location carefully.',
        seedling='Fill in trench gradually as crowns grow. Do not harvest first year. Second year, harvest lightly for 2 weeks only.',
        vegetative='Allow ferns to grow fully each season — they power the crowns for next year\'s spears. Fertilize in spring and fall.',
        flowering='Female plants (red berries) put energy into seed production. Male-only varieties (Jersey series) produce more spears.',
        harvest='From year 3 onwards, harvest spears when 6–8" tall and tips are still tight. Cut or snap at soil level. Season lasts 6–8 weeks.',
    ),
    faqs=[
        dict(q='How long before asparagus produces?', a='Asparagus requires patience — 2–3 years before full harvest begins. But a well-maintained bed produces for 20–30 years.'),
        dict(q='Why does asparagus make urine smell odd?', a='Asparagusic acid breaks down into sulfur-containing compounds. The ability to detect this is genetic — about 25% of people cannot smell it.'),
    ],
    nutrition=dict(serving_size='5 spears (90g)', calories=20, protein_g=2.2, carbs_g=3.7, fiber_g=1.8, fat_g=0.2,
        vitamins=['Folate: 18% DV','Vitamin K: 57% DV','Vitamin C: 12% DV','Vitamin A: 8% DV'],
        notes='One of the best dietary sources of folate. Contains inulin, a prebiotic fiber that feeds beneficial gut bacteria.'),
),
'Eggplant': dict(
    difficulty='Challenging', min_zone=5, max_zone=12, temp_min_f=60, temp_max_f=95,
    soil_ph_min=5.5, soil_ph_max=6.8, soil_type='Rich, well-draining loam; warm soil essential',
    good_neighbors=['Bean','Pepper','Tomato','Marigold','Basil'],
    bad_neighbors=['Fennel','Corn'],
    sow_indoor_weeks=10, direct_sow_offset=None, transplant_offset=3,
    how_to_grow=dict(
        starting='Start indoors 8–10 weeks before last frost. Eggplant needs warm germination (80–85°F) and is slow-growing.',
        seedling='Keep at 70°F+. Eggplant hates cold — even 50°F can cause permanent setback. Do not rush transplanting.',
        vegetative='Transplant into full sun only when nights are reliably above 55°F. Mulch well to retain soil heat.',
        flowering='Purple flowers need pollination. Tap flowers or use an electric toothbrush to vibrate them. Avoid temperature extremes during flowering.',
        harvest='Harvest when skin is glossy. Press gently — flesh should spring back. A dull skin means overripe and bitter.',
    ),
    faqs=[
        dict(q='Why does eggplant taste bitter?', a='Overripe eggplant or certain varieties can be bitter. Harvest while skin is glossy. Salting and rinsing cut eggplant draws out bitter compounds.'),
        dict(q='Why does my eggplant not set fruit?', a='Temperature is most likely — eggplant drops flowers below 55°F nights or above 95°F. Flea beetles are also a common issue; use row covers when young.'),
    ],
    nutrition=dict(serving_size='1 cup cooked (99g)', calories=35, protein_g=0.8, carbs_g=8.7, fiber_g=2.5, fat_g=0.2,
        vitamins=['Manganese: 10% DV','Folate: 5% DV','Potassium: 5% DV','Vitamin C: 4% DV'],
        notes='Eggplant skin contains nasunin, an anthocyanin antioxidant that protects brain cell membranes.'),
),
'Sweet Potato': dict(
    difficulty='Easy', min_zone=5, max_zone=11, temp_min_f=60, temp_max_f=95,
    soil_ph_min=5.5, soil_ph_max=6.5, soil_type='Loose, well-draining sandy loam; low nitrogen',
    good_neighbors=['Bean','Oregano','Thyme'],
    bad_neighbors=['Squash','Tomato'],
    sow_indoor_weeks=None, direct_sow_offset=None, transplant_offset=4,
    how_to_grow=dict(
        starting='Plant "slips" (rooted cuttings from sweet potato) 3–4 weeks after last frost. Grow slips from a whole sweet potato in water starting 6 weeks before planting.',
        seedling='Plant slips 12" apart in raised rows or mounds. Soil temperature must be above 60°F.',
        vegetative='Vines spread 4–6 feet. Minimal care needed. Avoid high-nitrogen fertilizer — promotes leafy growth over tuber development.',
        flowering='Rarely flowers in northern climates. Not required for tuber production.',
        harvest='Harvest before first frost, 90–120 days after planting. Dig carefully to avoid bruising. Cure at 80–85°F with high humidity for 1–2 weeks to convert starches to sugars.',
    ),
    faqs=[
        dict(q='Are sweet potatoes and yams the same?', a='No. True yams are a different species (Dioscorea) grown in tropical Africa and Asia. Most "yams" sold in US stores are actually sweet potatoes.'),
        dict(q='Why are my sweet potatoes small?', a='Poor drainage, compacted soil, too much nitrogen, or insufficient growing time. Ensure loose, sandy soil and a long, warm growing season.'),
    ],
    nutrition=dict(serving_size='1 medium baked (130g)', calories=112, protein_g=2.0, carbs_g=26.0, fiber_g=3.8, fat_g=0.1,
        vitamins=['Vitamin A: 438% DV','Vitamin C: 37% DV','Potassium: 15% DV','Vitamin B6: 16% DV'],
        notes='One of the most nutritious vegetables. The orange color indicates massive beta-carotene content. Eating with a little fat increases absorption.'),
),
'Celery': dict(
    difficulty='Challenging', min_zone=2, max_zone=10, temp_min_f=40, temp_max_f=75,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Rich, moist loam with high organic matter; consistent moisture',
    good_neighbors=['Tomato','Bean','Leek','Onion','Cabbage'],
    bad_neighbors=['Corn','Potato','Aster'],
    sow_indoor_weeks=12, direct_sow_offset=None, transplant_offset=0,
    how_to_grow=dict(
        starting='Start indoors 10–12 weeks before last frost. Celery is slow to germinate (14–21 days) and requires light to germinate — press into surface.',
        seedling='Very slow-growing. Maintain consistent moisture and 65–70°F temperatures. Transplant carefully at 6" height.',
        vegetative='Needs consistent moisture — never dry out. Blanch stalks by mounding soil or wrapping in cardboard for white, milder stalks.',
        flowering='Celery left to overwinter will bolt in year 2. Flowers attract beneficial insects.',
        harvest='Harvest outer stalks from the base when thick enough, or pull whole plant.',
    ),
    faqs=[
        dict(q='Why is my celery bitter?', a='Heat stress, inconsistent watering, or insufficient nutrients cause bitterness. Keep plants moist and cool, and blanch for mild flavor.'),
        dict(q='Can I regrow celery from the base?', a='Yes — cut the base and place in shallow water on a sunny windowsill. It will regrow leaves and can be replanted outdoors.'),
    ],
    nutrition=dict(serving_size='1 cup chopped (101g)', calories=16, protein_g=0.7, carbs_g=3.0, fiber_g=1.6, fat_g=0.2,
        vitamins=['Vitamin K: 37% DV','Folate: 9% DV','Potassium: 8% DV','Vitamin C: 5% DV'],
        notes='Contains apigenin, a flavonoid with anti-inflammatory and anti-cancer research interest. Very low calorie for its volume.'),
),
'Leek': dict(
    difficulty='Moderate', min_zone=2, max_zone=10, temp_min_f=30, temp_max_f=80,
    soil_ph_min=6.0, soil_ph_max=8.0, soil_type='Rich, moist, well-draining loam',
    good_neighbors=['Carrot','Celery','Beet','Onion'],
    bad_neighbors=['Bean','Pea'],
    sow_indoor_weeks=12, direct_sow_offset=-6, transplant_offset=-4,
    how_to_grow=dict(
        starting='Start indoors 10–12 weeks before last frost. Sow thinly, ¼" deep.',
        seedling='Thin to 1" in flats. Transplant into deep trenches and backfill as they grow to blanch stems.',
        vegetative='Blanch by earthing up (mounding soil around stems). Deep planting and hilling produces long white shanks.',
        flowering='Biennial — bolts in second year. Harvest before bolt for best texture.',
        harvest='Harvest when shanks are thick (1–2"). Leeks tolerate hard frost in the ground — can harvest through winter.',
    ),
    faqs=[
        dict(q='How do I clean leeks of grit?', a='Trim roots and dark green tops. Slice lengthwise and rinse under running water, fanning leaves to remove all grit.'),
    ],
    nutrition=dict(serving_size='1 leek (89g)', calories=54, protein_g=1.3, carbs_g=12.6, fiber_g=1.6, fat_g=0.3,
        vitamins=['Vitamin K: 47% DV','Folate: 16% DV','Vitamin C: 12% DV','Manganese: 14% DV'],
        notes='Like onions and garlic, leeks contain allicin and are associated with cardiovascular and immune benefits.'),
),
# ── Herbs ──────────────────────────────────────────────────────────────────
'Basil': dict(
    difficulty='Easy', min_zone=10, max_zone=13, temp_min_f=50, temp_max_f=90,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Fertile, well-draining loam; warm',
    good_neighbors=['Tomato','Pepper','Oregano','Marigold'],
    bad_neighbors=['Sage','Rue'],
    sow_indoor_weeks=6, direct_sow_offset=2, transplant_offset=2,
    how_to_grow=dict(
        starting='Start indoors 4–6 weeks before last frost, or direct sow after last frost. Basil is extremely frost-sensitive.',
        seedling='Germination in 5–7 days at 70°F+. Pot up once true leaves appear. Never allow to get cold.',
        vegetative='Full sun. Water at base to prevent fungal diseases. Pinch flower buds regularly to encourage leafy growth.',
        flowering='Pinch flower buds as they appear. Basil that flowers puts energy into seeds, reducing leaf production and flavor.',
        harvest='Harvest from the top, cutting just above a leaf pair. The plant will branch and become bushier with each harvest.',
    ),
    faqs=[
        dict(q='Why is my basil turning black?', a='Cold damage. Even temperatures below 50°F can cause blackening. Keep basil warm at all times and away from cold windowsills and drafts.'),
        dict(q='How do I store fresh basil?', a='Store stems in a glass of water at room temperature (not the fridge — cold blackens leaves). Or make pesto and freeze in ice cube trays.'),
        dict(q='Why does my basil get leggy?', a='Not enough light. Basil needs 6+ hours of direct sun. Pinch the growing tip to encourage bushy growth.'),
    ],
    nutrition=dict(serving_size='¼ cup fresh (6g)', calories=1, protein_g=0.2, carbs_g=0.1, fiber_g=0.1, fat_g=0.1,
        vitamins=['Vitamin K: 22% DV','Vitamin A: 4% DV'],
        notes='Rich in eugenol, which has anti-inflammatory and antibacterial properties. Dried basil concentrates all nutrients.'),
),
'Cilantro': dict(
    difficulty='Easy', min_zone=2, max_zone=11, temp_min_f=50, temp_max_f=75,
    soil_ph_min=6.2, soil_ph_max=6.8, soil_type='Well-draining loam',
    good_neighbors=['Spinach','Pea','Tomato','Anise'],
    bad_neighbors=['Fennel','Dill (cross-pollinates)'],
    sow_indoor_weeks=None, direct_sow_offset=-2, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow only — dislikes transplanting. Sow ¼" deep in early spring or fall. In hot climates, grow in fall/winter.',
        seedling='Thin to 4–6". Cilantro grows quickly in cool weather.',
        vegetative='Cool-season herb. Bolts rapidly in heat. Succession plant every 3 weeks for continuous harvest.',
        flowering='Flowers (also called coriander) are highly attractive to beneficial insects. Seeds are the spice coriander.',
        harvest='Cut stems from outside in. Harvest frequently to delay bolting.',
    ),
    faqs=[
        dict(q='Why does cilantro taste like soap to some people?', a='About 10–15% of people have a genetic variant (OR6A2 gene) that makes cilantro smell and taste soapy. It is not possible to override this sensitivity.'),
        dict(q='How do I prevent cilantro from bolting?', a='Choose slow-bolt varieties, grow in cool weather, and avoid hot, dry conditions. Once bolting starts, it cannot be reversed.'),
    ],
    nutrition=dict(serving_size='¼ cup fresh (4g)', calories=1, protein_g=0.1, carbs_g=0.1, fiber_g=0.1, fat_g=0.0,
        vitamins=['Vitamin K: 12% DV','Vitamin A: 3% DV'],
        notes='Contains dodecanal, an antimicrobial compound effective against Salmonella. Coriander seeds (dried fruit) have different compounds and are used as a separate spice.'),
),
'Parsley': dict(
    difficulty='Moderate', min_zone=4, max_zone=9, temp_min_f=40, temp_max_f=80,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Rich, moist, well-draining loam',
    good_neighbors=['Asparagus','Carrot','Tomato','Rose'],
    bad_neighbors=['Onion','Garlic','Lettuce (nearby)'],
    sow_indoor_weeks=10, direct_sow_offset=-4, transplant_offset=None,
    how_to_grow=dict(
        starting='Soak seeds 24 hours before planting. Germination is very slow (3–4 weeks) even indoors. Start 10–12 weeks before last frost.',
        seedling='Thin to 6–8". Parsley is a biennial — Year 1: leaves; Year 2: flowers and seeds.',
        vegetative='Keep moist. Parsley tolerates partial shade. Mulch in winter to overwinter in zones 5–6.',
        flowering='Second-year plants bolt and flower. Leaf quality declines. Flowers attract beneficial wasps.',
        harvest='Cut outer stems at the base. Inner stems and center continue to grow. Harvest regularly for best production.',
    ),
    faqs=[
        dict(q='Why is my parsley slow to germinate?', a='Parsley has naturally slow germination (21–28 days). Soaking seeds 24 hours before planting, or pouring boiling water over the row, speeds germination.'),
        dict(q='Flat vs curly parsley — which is better?', a='Flat-leaf (Italian) parsley has more flavor and is preferred for cooking. Curly parsley is milder and used more as a garnish.'),
    ],
    nutrition=dict(serving_size='¼ cup fresh (15g)', calories=5, protein_g=0.5, carbs_g=1.0, fiber_g=0.5, fat_g=0.1,
        vitamins=['Vitamin K: 154% DV','Vitamin C: 22% DV','Vitamin A: 13% DV','Folate: 11% DV'],
        notes='Parsley contains apigenin and luteolin, antioxidants with anti-inflammatory activity. Very high in vitamin K per serving.'),
),
'Dill': dict(
    difficulty='Easy', min_zone=2, max_zone=11, temp_min_f=45, temp_max_f=85,
    soil_ph_min=5.8, soil_ph_max=7.5, soil_type='Light, well-draining loam',
    good_neighbors=['Cabbage','Onion','Lettuce','Cucumber'],
    bad_neighbors=['Carrot','Tomato','Fennel (cross-pollinates)'],
    sow_indoor_weeks=None, direct_sow_offset=-2, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow only — has taproot, dislikes transplanting. Sow thinly ¼" deep. Succession plant every 3 weeks.',
        seedling='Thin to 6–9". Fast-growing in cool weather.',
        vegetative='Grows 2–4 ft tall. May need staking in wind. Bolts in heat — plant in spring and fall.',
        flowering='Flat-topped yellow flowers (umbels) attract enormous numbers of beneficial insects. Allow to flower if you want dill seeds.',
        harvest='Harvest leaves (fronds) anytime. Cut flower heads when half the flowers are open for drying. Harvest seeds when brown.',
    ),
    faqs=[
        dict(q='Why does my dill bolt so fast?', a='Dill is naturally a cool-weather plant. Hot weather and long days trigger bolting. Plant in early spring and again in late summer for fall.'),
        dict(q='Can I grow dill near fennel?', a='Avoid planting them together — they cross-pollinate and the resulting seeds may have inferior flavor.'),
    ],
    nutrition=dict(serving_size='1 tbsp fresh (1g)', calories=0, protein_g=0.1, carbs_g=0.1, fiber_g=0.0, fat_g=0.0,
        vitamins=['Vitamin A: 1% DV','Vitamin C: 1% DV'],
        notes='Dill seeds are higher in nutrients than leaves. Contains carvone, an essential oil with antimicrobial and digestive benefits.'),
),
'Mint': dict(
    difficulty='Easy', min_zone=3, max_zone=11, temp_min_f=32, temp_max_f=85,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Moist, rich loam; any soil with consistent moisture',
    good_neighbors=['Cabbage','Tomato','Pea','Carrot'],
    bad_neighbors=['Chamomile','Parsley'],
    sow_indoor_weeks=None, direct_sow_offset=0, transplant_offset=0,
    how_to_grow=dict(
        starting='Best propagated from divisions or cuttings — seed-grown mint is variable. Plant divisions after last frost.',
        seedling='Mint establishes quickly. Plant in a container or use a buried pot to contain its aggressive spreading.',
        vegetative='Highly invasive via underground runners (rhizomes). Grows in partial shade — one of the few herbs that tolerates it.',
        flowering='Flowering reduces leaf quality. Cut flower spikes as they appear to maintain leaf production.',
        harvest='Cut stems frequently. Harvest in the morning for best essential oil content. Cut back to 3" height after flowering.',
    ),
    faqs=[
        dict(q='How do I stop mint from spreading?', a='Plant in a container buried in the ground up to the rim, or in a raised bed with solid sides. Remove any runners that escape promptly.'),
        dict(q='Can I grow mint indoors?', a='Yes — mint grows well on a sunny kitchen windowsill in a pot. It needs at least 4 hours of sun or bright grow light.'),
    ],
    nutrition=dict(serving_size='2 tbsp fresh (3g)', calories=2, protein_g=0.1, carbs_g=0.4, fiber_g=0.3, fat_g=0.0,
        vitamins=['Vitamin A: 3% DV','Vitamin C: 2% DV'],
        notes='Menthol, the key compound in mint, has been shown to relieve IBS symptoms, headaches, and nasal congestion.'),
),
'Rosemary': dict(
    difficulty='Easy', min_zone=7, max_zone=11, temp_min_f=20, temp_max_f=90,
    soil_ph_min=6.0, soil_ph_max=8.0, soil_type='Sandy, very well-draining; tolerates poor, dry soils',
    good_neighbors=['Sage','Thyme','Cabbage','Bean','Carrot'],
    bad_neighbors=['Mint','Pumpkin','Cucumber'],
    sow_indoor_weeks=None, direct_sow_offset=None, transplant_offset=2,
    how_to_grow=dict(
        starting='Start from cuttings or nursery transplants. Rosemary seeds germinate erratically and take months. Take 4" cuttings from new growth in spring.',
        seedling='Root cuttings in moist potting mix or in a glass of water. Transplant when rooted.',
        vegetative='Needs excellent drainage — will rot in wet soil. Once established, drought-tolerant. Feed lightly with balanced fertilizer in spring.',
        flowering='Blue or purple flowers appear in spring. Edible and attractive to bees. Light pruning after flowering encourages dense growth.',
        harvest='Snip stems from the top. Never cut more than ⅓ of the plant at once. Grows slowly from woody stems.',
    ),
    faqs=[
        dict(q='Can rosemary survive winter?', a='In zones 7+, rosemary is perennial. In zones 6 and below, grow in containers and bring indoors. Very well-drained soil is essential for winter survival.'),
        dict(q='Why is my rosemary wilting even when watered?', a='Root rot from overwatering or poor drainage. Rosemary needs very fast-draining soil. Let soil dry completely between waterings.'),
    ],
    nutrition=dict(serving_size='1 tsp dried (1g)', calories=4, protein_g=0.1, carbs_g=0.8, fiber_g=0.5, fat_g=0.2,
        vitamins=['Vitamin A: 2% DV','Iron: 3% DV'],
        notes='Contains rosmarinic acid and carnosic acid, potent antioxidants with neuroprotective and anti-inflammatory properties.'),
),
'Thyme': dict(
    difficulty='Easy', min_zone=5, max_zone=11, temp_min_f=20, temp_max_f=90,
    soil_ph_min=6.0, soil_ph_max=8.0, soil_type='Sandy, well-draining; tolerates dry, poor soils',
    good_neighbors=['Cabbage','Rosemary','Eggplant','Potato','Strawberry'],
    bad_neighbors=['Mint','Chives'],
    sow_indoor_weeks=8, direct_sow_offset=0, transplant_offset=0,
    how_to_grow=dict(
        starting='Start from seed 8–10 weeks before last frost, or grow from divisions/cuttings. Seeds germinate in 14–21 days.',
        seedling='Pot up once established. Transplant after last frost. Harden off thoroughly.',
        vegetative='Very drought-tolerant once established. Excellent drainage is essential. Hardy perennial in zones 5–9.',
        flowering='Small pink/lavender flowers are edible and attract bees. Prune back after flowering by one-third.',
        harvest='Harvest fresh sprigs anytime. Flavor is strongest just before flowering. Cut stems, not individual leaves.',
    ),
    faqs=[
        dict(q='Is thyme perennial or annual?', a='Perennial in zones 5–9. Grows as an annual in colder climates. Bring containers indoors over winter in zones 4 and below.'),
        dict(q='When is thyme most flavorful?', a='Just before and during flowering, when essential oil content is highest. Harvest in the morning after dew has dried.'),
    ],
    nutrition=dict(serving_size='1 tsp fresh (1g)', calories=1, protein_g=0.1, carbs_g=0.2, fiber_g=0.1, fat_g=0.0,
        vitamins=['Vitamin C: 2% DV','Vitamin A: 2% DV'],
        notes='Thymol, thyme\'s key compound, is a natural antiseptic used in mouthwashes and cleaning products. Strong antimicrobial properties.'),
),
'Oregano': dict(
    difficulty='Easy', min_zone=5, max_zone=11, temp_min_f=20, temp_max_f=90,
    soil_ph_min=6.0, soil_ph_max=8.0, soil_type='Sandy, well-draining; prefers dry, rocky soil',
    good_neighbors=['Tomato','Pepper','Basil','Asparagus'],
    bad_neighbors=['Mint'],
    sow_indoor_weeks=8, direct_sow_offset=0, transplant_offset=0,
    how_to_grow=dict(
        starting='Start from seed 8–10 weeks before last frost or grow from divisions. Seeds germinate in 7–14 days.',
        seedling='Grow at 65–70°F. Transplant after last frost. Space 12" apart.',
        vegetative='Drought-tolerant perennial. Lean soil produces more flavorful leaves (stress concentrates essential oils).',
        flowering='Harvest before and during flowering for best flavor. Cut back after flowering.',
        harvest='Harvest frequently. Flavor is strongest just before bloom. Cut stems to within 2–3" of base.',
    ),
    faqs=[
        dict(q='Greek vs Italian oregano — what is the difference?', a='Greek oregano (O. vulgare subsp. hirtum) is more intensely flavored and is the culinary standard. Italian oregano is milder.'),
        dict(q='Does oregano need to be fertilized?', a='Minimal feeding needed. Too much fertilizer reduces the concentration of essential oils and weakens flavor.'),
    ],
    nutrition=dict(serving_size='1 tsp dried (1g)', calories=3, protein_g=0.1, carbs_g=0.7, fiber_g=0.4, fat_g=0.1,
        vitamins=['Vitamin K: 8% DV','Iron: 4% DV'],
        notes='Contains carvacrol and thymol, compounds with powerful antibacterial properties. Higher antioxidant activity than many fruits and vegetables by weight.'),
),
'Chives': dict(
    difficulty='Easy', min_zone=3, max_zone=10, temp_min_f=25, temp_max_f=85,
    soil_ph_min=6.0, soil_ph_max=7.0, soil_type='Moist, fertile loam',
    good_neighbors=['Carrot','Tomato','Apple tree','Parsley','Parsnip'],
    bad_neighbors=['Bean','Pea'],
    sow_indoor_weeks=8, direct_sow_offset=-2, transplant_offset=0,
    how_to_grow=dict(
        starting='Direct sow or start indoors 8 weeks before last frost. Chives establish slowly but are long-lived perennials.',
        seedling='Thin to 4–6". Slow to establish from seed — easier to divide an existing clump.',
        vegetative='Low-maintenance perennial. Divide every 3–4 years. Cut back to 2" after flowering to rejuvenate.',
        flowering='Pink-purple spherical flowers are edible and beautiful. Great for edible garnish. Deadhead to prevent self-seeding.',
        harvest='Cut leaves 2" above soil level. Plants regrow rapidly. Harvest 3–4 times per season.',
    ),
    faqs=[
        dict(q='Can I grow chives indoors?', a='Yes — chives grow well in a sunny window. Pot up a clump from outside in fall or grow from seed indoors year-round.'),
    ],
    nutrition=dict(serving_size='1 tbsp fresh (3g)', calories=1, protein_g=0.1, carbs_g=0.1, fiber_g=0.1, fat_g=0.0,
        vitamins=['Vitamin K: 4% DV','Vitamin A: 2% DV','Vitamin C: 2% DV'],
        notes='Like all alliums, chives contain organosulfur compounds that support cardiovascular health and immunity.'),
),
'Sage': dict(
    difficulty='Easy', min_zone=4, max_zone=11, temp_min_f=25, temp_max_f=90,
    soil_ph_min=5.5, soil_ph_max=8.0, soil_type='Sandy, well-draining; tolerates dry soils',
    good_neighbors=['Rosemary','Carrot','Brassica','Tomato'],
    bad_neighbors=['Basil','Onion','Rue'],
    sow_indoor_weeks=6, direct_sow_offset=0, transplant_offset=0,
    how_to_grow=dict(
        starting='Start from seed 6–8 weeks before last frost, or easier from cuttings/divisions.',
        seedling='Transplant after last frost. Space 18–24" apart.',
        vegetative='Drought-tolerant once established. Excellent drainage essential. Replace plants every 3–4 years as woody growth reduces production.',
        flowering='Blue flowers are edible. Prune after flowering to keep compact.',
        harvest='Harvest lightly in first year to allow establishment. From year 2, harvest freely.',
    ),
    faqs=[
        dict(q='Why is my sage getting woody and sparse?', a='Sage becomes woody and less productive after 3–4 years. Replace with new plants or rejuvenate by hard pruning in spring.'),
    ],
    nutrition=dict(serving_size='1 tsp dried (1g)', calories=2, protein_g=0.1, carbs_g=0.4, fiber_g=0.3, fat_g=0.1,
        vitamins=['Vitamin K: 8% DV','Iron: 2% DV'],
        notes='Research suggests sage may improve memory and cognitive function. Contains rosmarinic acid and carnosic acid, powerful antioxidants.'),
),
'Fennel': dict(
    difficulty='Easy', min_zone=4, max_zone=11, temp_min_f=40, temp_max_f=85,
    soil_ph_min=5.5, soil_ph_max=8.0, soil_type='Well-draining, light loam',
    good_neighbors=['Dill (keep separated)'],
    bad_neighbors=['Tomato','Pepper','Bean','Brassicas','Coriander','Almost all vegetables'],
    sow_indoor_weeks=None, direct_sow_offset=-2, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow only — taproot makes transplanting difficult. Sow ¼" deep in spring.',
        seedling='Thin to 12". Fennel grows large — keep isolated from vegetables.',
        vegetative='Keep fennel isolated in its own bed or containers. Its root exudates inhibit many vegetables.',
        flowering='Yellow umbrella flowers attract huge numbers of beneficial insects. Allow to flower for wildlife benefit.',
        harvest='For Florence fennel (bulbing type): harvest bulb when tennis-ball sized. For herb fennel: harvest fronds anytime; harvest seeds when brown.',
    ),
    faqs=[
        dict(q='Why should fennel be kept away from other plants?', a='Fennel produces allelopathic compounds that inhibit the growth of many vegetables, especially tomatoes, beans, and brassicas. Grow it in its own bed.'),
        dict(q='Florence fennel vs herb fennel — what\'s the difference?', a='Florence fennel is grown for its large, bulbous base used as a vegetable. Herb fennel is grown for leaves and seeds.'),
    ],
    nutrition=dict(serving_size='1 cup sliced bulb (87g)', calories=27, protein_g=1.1, carbs_g=6.3, fiber_g=2.7, fat_g=0.2,
        vitamins=['Vitamin C: 17% DV','Folate: 6% DV','Potassium: 8% DV','Vitamin B6: 4% DV'],
        notes='Contains anethole, which gives fennel its anise-like flavor. Anethole has anti-inflammatory and antimicrobial properties.'),
),
'Lavender': dict(
    difficulty='Moderate', min_zone=5, max_zone=9, temp_min_f=10, temp_max_f=85,
    soil_ph_min=6.5, soil_ph_max=7.5, soil_type='Sandy, very well-draining, alkaline; poor fertility preferred',
    good_neighbors=['Rosemary','Thyme','Sage','Rose','Brassicas'],
    bad_neighbors=['Mint','Fern','Impatiens'],
    sow_indoor_weeks=10, direct_sow_offset=None, transplant_offset=2,
    how_to_grow=dict(
        starting='Best propagated from cuttings — seeds have poor germination rates and plants are variable. Take 3–4" softwood cuttings in spring.',
        seedling='Germination from seed takes 2–4 weeks and is unreliable. Maintain low humidity to prevent damping off.',
        vegetative='Needs excellent drainage and full sun. Excess moisture causes root rot. Does not need fertilizing — lean soil is preferred.',
        flowering='Blooms June–August. Harvest flower spikes when ⅓ of florets have opened for longest-lasting dried lavender.',
        harvest='Cut stems 2–3" above woody growth. Never cut into old wood. Harvest in dry conditions.',
    ),
    faqs=[
        dict(q='Why does my lavender keep dying?', a='Poor drainage is the #1 killer. Lavender must have fast-draining soil. Raised beds or adding gravel/sand to clay soils helps enormously.'),
        dict(q='Can lavender grow in containers?', a='Yes — containers allow excellent drainage control. Use a gritty potting mix with added perlite.'),
    ],
    nutrition=dict(serving_size='Culinary use (small amounts)', calories=0, protein_g=0.0, carbs_g=0.0, fiber_g=0.0, fat_g=0.0,
        vitamins=['Used in very small culinary quantities'],
        notes='Primarily valued for its essential oil (linalool), which has demonstrated anxiolytic, sedative, and antimicrobial effects. Used in teas and baking.'),
),
'Lemon Balm': dict(
    difficulty='Easy', min_zone=3, max_zone=9, temp_min_f=25, temp_max_f=85,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Well-draining loam; adapts to most soils',
    good_neighbors=['Tomato','Squash','Melon','All vegetables (general beneficial)'],
    bad_neighbors=[],
    sow_indoor_weeks=8, direct_sow_offset=0, transplant_offset=0,
    how_to_grow=dict(
        starting='Start from seed indoors 6–8 weeks before last frost, or grow from divisions. Self-seeds readily.',
        seedling='Thin to 12–18". Lemon balm establishes quickly.',
        vegetative='Vigorous grower; may spread aggressively. Contains in pots or divide regularly. Tolerates partial shade.',
        flowering='Deadhead to prevent excessive self-seeding. Flowers attract bees.',
        harvest='Harvest leaves before flowering for best lemony flavor. Cut stems to 2" to encourage bushy regrowth.',
    ),
    faqs=[
        dict(q='How is lemon balm used?', a='Fresh leaves in teas, salads, fish dishes, and desserts. Lemon balm tea is a traditional remedy for anxiety, insomnia, and cold sores.'),
    ],
    nutrition=dict(serving_size='1 cup tea', calories=2, protein_g=0.0, carbs_g=0.5, fiber_g=0.0, fat_g=0.0,
        vitamins=['Trace amounts of Vitamin C and antioxidants'],
        notes='Rosmarinic acid in lemon balm inhibits GABA transaminase, producing a calming effect. Clinical trials support use for anxiety and insomnia.'),
),
# ── Fruits ─────────────────────────────────────────────────────────────────
'Strawberry': dict(
    difficulty='Easy', min_zone=3, max_zone=10, temp_min_f=25, temp_max_f=85,
    soil_ph_min=5.5, soil_ph_max=6.5, soil_type='Sandy loam with high organic matter; excellent drainage',
    good_neighbors=['Bean','Spinach','Lettuce','Thyme','Sage'],
    bad_neighbors=['Brassicas','Fennel','Garlic (check variety)'],
    sow_indoor_weeks=None, direct_sow_offset=None, transplant_offset=-2,
    how_to_grow=dict(
        starting='Plant bare-root crowns or transplants 2–4 weeks before last frost. June-bearing produce one large crop; everbearing produce all season.',
        seedling='Plant with crown at soil level — too deep or shallow causes failure. Water in well.',
        vegetative='Mulch heavily with straw (hence the name). Water consistently. Remove runners (or let run to fill bed).',
        flowering='Remove all flowers in year 1 to direct energy into root development. Year 2+ let fruit develop.',
        harvest='Harvest when fully red and fragrant. Check daily. Berries do not continue to ripen once picked.',
    ),
    faqs=[
        dict(q='June-bearing vs everbearing — which is better?', a='June-bearers produce one large, concentrated crop ideal for preserving. Everbearers produce smaller quantities all season — better for fresh eating.'),
        dict(q='How do I renew a strawberry bed?', a='After harvest, mow leaves to 3" (not the crown), thin plants to 6" apart, fertilize, and water. Renovate every 3 years for best yields.'),
    ],
    nutrition=dict(serving_size='1 cup (152g)', calories=49, protein_g=1.0, carbs_g=11.7, fiber_g=3.0, fat_g=0.5,
        vitamins=['Vitamin C: 149% DV','Manganese: 29% DV','Folate: 9% DV','Potassium: 7% DV'],
        notes='One of the highest vitamin C foods. Rich in anthocyanins (the red pigment) with anti-inflammatory and heart-protective effects.'),
),
'Watermelon': dict(
    difficulty='Moderate', min_zone=3, max_zone=11, temp_min_f=65, temp_max_f=95,
    soil_ph_min=6.0, soil_ph_max=6.8, soil_type='Sandy loam, well-draining; warm and fertile',
    good_neighbors=['Corn','Sunflower','Nasturtium','Radish'],
    bad_neighbors=['Potato','Cucumber (space competition)'],
    sow_indoor_weeks=4, direct_sow_offset=2, transplant_offset=2,
    how_to_grow=dict(
        starting='Start indoors 3–4 weeks before last frost in warm conditions. Or direct sow when soil is 70°F+.',
        seedling='Transplant carefully — taproot sensitive. Biodegradable pots recommended.',
        vegetative='Needs 6–8 ft of space per plant. Mulch with black plastic to warm soil. Water deeply but infrequently.',
        flowering='Female flowers have tiny watermelon at base. Bees needed. One female flower per vine for large fruit (remove extras).',
        harvest='Rap with knuckles — hollow thud means ripe. Check tendril nearest fruit — dry and brown means ripe. Yellow ground spot.',
    ),
    faqs=[
        dict(q='How do I know when a watermelon is ripe?', a='Three signs: the tendril nearest the fruit turns brown and dry; the bottom (ground) spot turns from white to creamy yellow; and rapping the melon produces a hollow thud.'),
        dict(q='Can I grow watermelon in a small garden?', a='Choose bush or personal-size varieties (Faerie, Sugar Baby). Still needs 4+ feet of space, or train vertically with fruit supported in hammocks.'),
    ],
    nutrition=dict(serving_size='2 cups diced (280g)', calories=85, protein_g=1.7, carbs_g=21.6, fiber_g=1.1, fat_g=0.4,
        vitamins=['Vitamin C: 25% DV','Vitamin A: 18% DV','Potassium: 8% DV','Lycopene: ~15mg'],
        notes='92% water content makes it highly hydrating. Among the richest sources of lycopene — the red pigment with potent antioxidant and heart-protective effects.'),
),
# ── Flowers ─────────────────────────────────────────────────────────────────
'Sunflower': dict(
    difficulty='Easy', min_zone=2, max_zone=11, temp_min_f=55, temp_max_f=95,
    soil_ph_min=6.0, soil_ph_max=7.5, soil_type='Well-draining; tolerates poor, dry soils',
    good_neighbors=['Cucumber','Corn','Tomato','Squash','Melon'],
    bad_neighbors=['Potato','Bean (allelopathic — some varieties)'],
    sow_indoor_weeks=None, direct_sow_offset=2, transplant_offset=None,
    how_to_grow=dict(
        starting='Direct sow 1" deep after last frost when soil is 50°F+. Very easy to grow.',
        seedling='Thin to 12–24" depending on variety. No transplanting needed.',
        vegetative='Drought-tolerant once established. Stake tall varieties in windy locations.',
        flowering='Blooms in mid-summer. Each "flower" is actually thousands of tiny flowers in the disk. Bees and butterflies will flock to them.',
        harvest='For seeds: leave heads on plant until back of head turns brown. Cut with 12" of stem and hang to dry 2–3 weeks. For cut flowers: harvest when half the petals are open.',
    ),
    faqs=[
        dict(q='Do sunflowers need to be staked?', a='Standard tall varieties (6–10 ft) may need staking in wind. Dwarf varieties are self-supporting.'),
        dict(q='Are all sunflowers edible?', a='The seeds of all sunflowers are edible, though oil-type varieties have thin-shelled seeds. Petals are also edible and have a mildly nutty flavor.'),
    ],
    nutrition=dict(serving_size='¼ cup seeds (35g)', calories=207, protein_g=5.8, carbs_g=7.0, fiber_g=3.1, fat_g=19.0,
        vitamins=['Vitamin E: 66% DV','Thiamine: 28% DV','Selenium: 21% DV','Magnesium: 26% DV'],
        notes='Sunflower seeds are one of the richest plant sources of vitamin E (tocopherol), a fat-soluble antioxidant protecting cells from oxidative damage.'),
),
}


def main():
    conn = sqlite3.connect(DB)
    cur = conn.cursor()

    # Ensure all new columns exist
    existing_cols = [r[1] for r in cur.execute('PRAGMA table_info(plant_library)').fetchall()]
    new_cols = [
        ('difficulty','TEXT'), ('min_zone','INTEGER'), ('max_zone','INTEGER'),
        ('temp_min_f','INTEGER'), ('temp_max_f','INTEGER'),
        ('soil_ph_min','REAL'), ('soil_ph_max','REAL'), ('soil_type','TEXT'),
        ('good_neighbors','TEXT'), ('bad_neighbors','TEXT'),
        ('sow_indoor_weeks','INTEGER'), ('direct_sow_offset','INTEGER'), ('transplant_offset','INTEGER'),
        ('how_to_grow','TEXT'), ('faqs','TEXT'), ('nutrition','TEXT'),
    ]
    for col, coltype in new_cols:
        if col not in existing_cols:
            cur.execute(f'ALTER TABLE plant_library ADD COLUMN {col} {coltype}')
            print(f'Added column: {col}')

    updated = 0
    skipped = 0
    for name, data in PLANTS.items():
        row = cur.execute('SELECT id FROM plant_library WHERE name = ?', (name,)).fetchone()
        if not row:
            print(f'SKIP (not found): {name}')
            skipped += 1
            continue
        cur.execute('''
            UPDATE plant_library SET
                difficulty=?, min_zone=?, max_zone=?, temp_min_f=?, temp_max_f=?,
                soil_ph_min=?, soil_ph_max=?, soil_type=?,
                good_neighbors=?, bad_neighbors=?,
                sow_indoor_weeks=?, direct_sow_offset=?, transplant_offset=?,
                how_to_grow=?, faqs=?, nutrition=?
            WHERE name=?
        ''', (
            data.get('difficulty'),
            data.get('min_zone'), data.get('max_zone'),
            data.get('temp_min_f'), data.get('temp_max_f'),
            data.get('soil_ph_min'), data.get('soil_ph_max'),
            data.get('soil_type'),
            json.dumps(data.get('good_neighbors', [])),
            json.dumps(data.get('bad_neighbors', [])),
            data.get('sow_indoor_weeks'),
            data.get('direct_sow_offset'),
            data.get('transplant_offset'),
            json.dumps(data.get('how_to_grow')) if data.get('how_to_grow') else None,
            json.dumps(data.get('faqs')) if data.get('faqs') else None,
            json.dumps(data.get('nutrition')) if data.get('nutrition') else None,
            name,
        ))
        print(f'Updated: {name}')
        updated += 1

    conn.commit()
    conn.close()
    print(f'\nDone. {updated} plants updated, {skipped} skipped.')


if __name__ == '__main__':
    main()
